measure-sh/measure

docs/CONTRIBUTING.md
- add instructions to install deps for dashboard
=> docs: update contributing.md

.github/workflows/api.yml, .github/workflows/cleanup.yml, .github/workflows/dashboard.yml, .github/workflows/symbolicator-android.yml
- add tag trigger for api workflow
- add tag trigger for cleanup workflow
- add tag trigger for symbolicator-android workflow
- add tag trigger for dashboard workflow
=> ci: update workflow triggers

.github/workflows/api.yml, .github/workflows/cleanup.yml, .github/workflows/dashboard.yml, .github/workflows/symbolicator-android.yml
Enable build attestation for OCI images
- add build attestation for api image
- add build attestation for cleanup image
- add build attestation for dashboard image
- add build attestation for symbolicator-android image
=> ci: update workflows

README.md
=> docs: add team section to README

docs/hosting/README.md
- fix minor formatting issue in self host guide
=> docs: fix formatting

.github/workflows/changelog.yml
=> ci: fix changelog generation

.github/workflows/changelog.yml
- fix git push command to push changelog
=> ci: fix git push

README.md
=> docs: add discord link to README

.github/ISSUE_TEMPLATE/feature_request.md
=> docs: add feature request template

.github/ISSUE_TEMPLATE/bug_report.md
=> docs: add issue template

frontend/dashboard/app/components/journey.tsx
Removes commented code in `journey.tsx`
Closes #1147
=> chore(frontend): remove commented code

self-host/sessionator/README.md
Some minor updates and improvements to be more accurate and succicnt.
=> docs(backend): improve sessionator readme

android/CHANGELOG.md, android/gradle.properties, docs/android/README.md
=> chore(android): prepare sdk release v0.6.1

self-host/clickhouse/README.md, self-host/postgres/README.md
Made minor language and formatting improvements to postgres and clickhouse readmes. The contents and instructions are now consistent across both the documents.
fixes #1195
=> docs: update database docs

ios/MeasureSDK/MeasureSDK.xcodeproj/project.pbxproj, ios/MeasureSDK/MeasureSDK/Measure.swift, ios/MeasureSDK/MeasureSDK/Utils/Logger.swift, ios/MeasureSDK/MeasureSDK/Utils/SignPost.swift
Add Signpost for performance testing in iOS. 
Closes #1207
=> add signpost to iOS

backend/api/group/group.go
Format and round crash and ANR percentage contribution.
fixes #1156
=> fix(backend): round crash and anr contribution

frontend/dashboard/app/api/api_calls.ts
Refactor filter application to api calls
Closes #1168
=> chore(frontend): refactor filter application to api calls

frontend/dashboard/app/components/journey.tsx
- Adds missing useEffect deps for journey
- Removes loading state for visual improvement
Fixes #1227
=> fix(frontend): add missing useEffect deps for journey

backend/api/main.go, backend/api/measure/app.go, frontend/dashboard/app/[teamId]/apps/page.tsx, frontend/dashboard/app/[teamId]/overview/page.tsx, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/[teamId]/team/page.tsx, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/create_app.tsx, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/components/exceptions_overview.tsx, frontend/dashboard/app/components/filters.tsx
1. Redesigns apps page to show one app at a time
2. Allows app renaming
3. Fixes broken sdk integration link
4. Clears api status message for team name change in teams page
Closes #1166, #1235, #1236
=> feat(frontend): redesign apps page

backend/api/filter/appfilter.go, backend/api/measure/app.go, backend/api/measure/event.go, frontend/dashboard/app/[teamId]/apps/page.tsx, frontend/dashboard/app/[teamId]/overview/page.tsx, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/dropdown_select.tsx, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/components/exceptions_details_plot.tsx, frontend/dashboard/app/components/exceptions_overview.tsx, frontend/dashboard/app/components/filters.tsx, frontend/dashboard/app/components/journey.tsx, frontend/dashboard/app/components/sessions_overview_plot.tsx
Adds filter for OS versions
Closes #1240
=> feat(frontend): add filter for OS versions

frontend/dashboard/app/components/filters.tsx
Adds 'Last 6 months' date range option to filters
Closes #1249
=> feat(frontend): add 'Last 6 months' date range option

backend/api/measure/app.go, backend/api/replay/critical.go, frontend/dashboard/app/[teamId]/sessions/[appId]/[sessionId]/page.tsx, frontend/dashboard/app/components/session_replay.tsx, frontend/dashboard/app/components/session_replay_event_accordion.tsx
Adds link to crash/anr details from session replay
Closes #1251
=> feat(frontend): link to crash/anr details from session replay

android/measure-android-gradle/src/main/kotlin/sh/measure/BuildUploadTask.kt, android/measure/src/main/java/sh/measure/android/exporter/HttpUrlConnectionClient.kt, android/measure/src/main/java/sh/measure/android/exporter/NetworkClient.kt, android/measure/src/test/java/sh/measure/android/exporter/NetworkClientTest.kt
* Parse API_URL correctly in both SDK and plugin.
* Log request URL and method. 
closes #1271
=> fix(android): incorrect URL parsing

frontend/dashboard/app/not-found.tsx
Adds a custom 404 page
Closes #1274
=> feat(frontend): add custom 404 page

docs/hosting/README.md
Add guide for upgrading self host installations.
fixes #1290
=> docs(backend): add self host upgrade guide

android/CHANGELOG.md, android/gradle.properties, docs/android/README.md
Prepare release measure-android SDK 0.7.0
=> chore(android): prepare sdk release 0.7.0

docs/CONTRIBUTING.md
- update the incorrect release one line command
- fix some typos
fixes #1292
=> docs: update release one liner command

frontend/dashboard/package-lock.json, frontend/dashboard/package.json
Fix frontend security issues as reported by Dependabot. The dependencies of following components got an upgrade.
- `frontend/dashboard`
fixes #1304
=> fix(frontend): improve security posture

backend/api/group/group.go, backend/api/measure/app.go
Minor refactor to add couple of missing db close statements
=> refactor(backend): missing db close

frontend/dashboard/app/[teamId]/apps/page.tsx, frontend/dashboard/app/[teamId]/overview/page.tsx, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/components/debounce_text_input.tsx, frontend/dashboard/app/components/dropdown_select.tsx, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/components/exceptions_overview.tsx, frontend/dashboard/app/components/filters.tsx, frontend/dashboard/app/components/session_replay.tsx
Add filters to url params
Closes #1217
=> feat(frontend): add filters to urls

frontend/dashboard/app/[teamId]/overview/page.tsx, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/components/journey_sankey.tsx, frontend/dashboard/package-lock.json, frontend/dashboard/package.json
Uses Sankey graphs for Journeys
Closes #1313
=> feat(frontend): use sankey graphs for journeys

frontend/dashboard/app/[teamId]/apps/page.tsx
Update app name on selected app change in Apps page dropdown
Fixes #1329
=> fix(frontend): update app name on selected app change

frontend/dashboard/app/components/filters.tsx
Disables appending filters to URLs
Fixes #1344
=> fix(frontend): disable appending filters to URLs

frontend/dashboard/app/components/exceptions_details_plot.tsx
Improves exceptions/anr details plot UI:
- Removes app versions legend and adds version to tooltip instead
- Makes use of legend area to make graph larger
- Changes x axis date labels rotation to improve legibility
- Increases symbol (dot) sizes
Fixes #1332
=> fix(frontend): improve exception/anr details plot ui

frontend/dashboard/app/components/dropdown_select.tsx
Limits height of dropdown component
https://github.com/user-attachments/assets/1fdedc65-9e98-4ca9-a809-3e0f66fc88f2
Fixes #1351
=> fix(frontend): limit height of dropdown component

frontend/dashboard/app/components/exceptions_details_plot.tsx, frontend/dashboard/app/components/exceptions_overview_plot.tsx, frontend/dashboard/app/components/filters.tsx, frontend/dashboard/app/components/journey_sankey.tsx, frontend/dashboard/app/components/loading_spinner.tsx, frontend/dashboard/app/components/sessions_overview_plot.tsx
Adds loading spinners for plot components
Closes #1352
=> chore(frontend): add loading spinners for plot components

ios/MeasureSDK/CoreData/Entities/EventEntity.swift, ios/MeasureSDK/CoreData/EventStore.swift, ios/MeasureSDK/XCDataModel/MeasureModel.xcdatamodeld/MeasureModel.xcdatamodel/contents
- Core data model updated to save gesture events data
- EventEntity updated
=> chore(ios): update event store to save gesture data

frontend/dashboard/app/[teamId]/layout.tsx, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/components/exceptions_overview.tsx
Persists paginator data via urls on exceptions overview to and sessions pages
Closes #1319
=> feat(frontend): persist paginator on master detail nav

frontend/dashboard/app/components/exceptions_overview_plot.tsx, frontend/dashboard/app/components/sessions_overview_plot.tsx
Remove legends & add versions in tooltips to exception & sessions overview plots
Closes #1371
=> chore(frontend): remove legends & add versions in tooltips to exception & sessions overview plots

frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/components/exceptions_overview.tsx, frontend/dashboard/app/components/filters.tsx, frontend/dashboard/app/components/info_circle_app_adoption.tsx, frontend/dashboard/app/components/info_circle_app_size.tsx, frontend/dashboard/app/components/info_circle_app_start_time.tsx, frontend/dashboard/app/components/info_circle_exception_rate.tsx, frontend/dashboard/app/components/loading_bar.tsx
Add loading states
Closes #1361
=> chore(frontend): add loading states

frontend/dashboard/app/[teamId]/layout.tsx, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/components/exceptions_overview.tsx
Reverts changes made to persist paginator range in urls due to it being flawed and buggy.
Fixes #1376
=> Revert "feat(frontend): persist paginator on master detail nav"

android/measure/src/androidTest/java/sh/measure/android/TestMeasureInitializer.kt, android/measure/src/main/java/sh/measure/android/MeasureInitializer.kt, android/measure/src/main/java/sh/measure/android/events/EventType.kt, android/measure/src/main/java/sh/measure/android/performance/ComponentCallbacksCollector.kt, android/measure/src/main/java/sh/measure/android/performance/MemoryEvents.kt, android/measure/src/main/java/sh/measure/android/storage/EventExtensions.kt, android/measure/src/test/java/sh/measure/android/fakes/TestData.kt, android/measure/src/test/java/sh/measure/android/performance/ComponentCallbacksCollectorTest.kt, android/measure/src/test/java/sh/measure/android/storage/EventExtensionsKtTest.kt, docs/android/features/feature_memory_monitoring.md, docs/api/sdk/README.md
Removes low memory event.
closes #560
=> chore(android): remove low memory event

README.md
Adds videos to README
Closes #1388
=> docs: add videos to README

android/measure/src/androidTest/java/sh/measure/android/TestMeasureInitializer.kt, android/measure/src/main/java/sh/measure/android/MeasureInitializer.kt, android/measure/src/main/java/sh/measure/android/RecentSession.kt, android/measure/src/main/java/sh/measure/android/SessionManager.kt, android/measure/src/main/java/sh/measure/android/attributes/AppAttributeProcessor.kt, android/measure/src/main/java/sh/measure/android/storage/PrefsStorage.kt, android/measure/src/main/java/sh/measure/android/utils/PackageInfoProviderImpl.kt, android/measure/src/test/java/sh/measure/android/SessionManagerTest.kt, android/measure/src/test/java/sh/measure/android/fakes/FakePackageInfoProvider.kt, android/measure/src/test/java/sh/measure/android/storage/PrefsStorageTest.kt
* Start a new session if app got updated since last session.
* Extract logic to get package info details into a single reusable class.
closes #1421
=> fix(android): create new session if app version changed since last

frontend/dashboard/app/components/filters.tsx
Updates default time filter to last 6 hours
Closes #1429
=> chore(frontend): update default time filter to last 6 hours

frontend/dashboard/app/components/exceptions_details.tsx
Improve exception details loading state
Closes #1425
=> chore(frontend): improve exception details loading state

frontend/dashboard/app/components/session_replay.tsx
Handle empty mem/cpu graph in session replay
Fixes #1426
=> fix(frontend): handle empty mem/cpu graph in session replay

frontend/dashboard/app/api/api_calls.ts
Some dashboard APIs were failing due to lack of URL encoding of query string values.
- fixes #1445
=> fix(frontend): some dashboard apis were failing due to lack of url encoding

README.md
=> docs: improve spelling in readme

README.md
Updates exceptions demo video in README
=> docs: update exceptions demo video in README

frontend/dashboard/app/[teamId]/layout.tsx, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/utils/auth/auth.ts
Cancels in-flight requests 
Closes #1469
=> chore(frontend): cancel in-flight requests

frontend/dashboard/app/[teamId]/layout.tsx, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/components/exceptions_overview.tsx, frontend/dashboard/app/utils/auth/auth.ts
Standardises paginator UI
Closes #1471
=> chore(frontend): standardise paginator UI

frontend/dashboard/app/components/filters.tsx
Sets default session type filter to all issues
Closes #1479
=> chore(frontend): set default session type filter to all issues

android/CHANGELOG.md, android/gradle.properties, docs/android/README.md
=> chore(android): prepare release android-v0.8.2

self-host/clickhouse/20241106132226_alter_sessions_table.sql
Add couple of skip indexes for Sessions table for faster lookups.
=> chore(backend): add skip indexes for sessions table

frontend/dashboard/app/[teamId]/sessions/page.tsx
Truncates matched free text
Fixes #1493
=> fix(frontend): truncate matched free text

frontend/dashboard/app/[teamId]/sessions/page.tsx
\# Description
Handles no data case for sessions list
Fixes #1495
=> fix(frontend): handle no data case for sessions list

docs/api/dashboard/README.md
Document GET `/apps/:id/sessions` API.
- fixes #1314
=> docs(backend): document sessions overview list api

docs/hosting/README.md, docs/hosting/migration-guides/README.md, docs/hosting/migration-guides/v0.4.x/README.md, self-host/migrations/README.md, self-host/migrations/v0.4.x-data-backfills.sh
Wrote introduction to Migration Guides and wrote a guide for v0.4.x. These guides contain clear, actionable information to make upgrading hassle free.
- fixes #1506
=> Migration guides

android/measure/src/main/java/sh/measure/android/MeasureInternal.kt, android/measure/src/main/java/sh/measure/android/exporter/Heartbeat.kt
Reverts usage of reentrant lock which was added in #1538. This is causing an issue where the heartbeat for export continues running after the app goes to background.
=> fix(android): revert usage of reentrant lock for heartbeat and SDK initialization

backend/api/measure/app.go
Small PR to remove a log line.
=> chore(backend): remove unused code

docs/api/dashboard/README.md
Update dashboard API docs to document the POST `/apps/:id/shortFilters` API
- fixes #1503
=> docs(backend): document short filters api

frontend/dashboard/app/components/filters.tsx
Deletes unused url filters code
Closes #1487
=> chore(frontend): delete unused url filters code

docs/ios/README.md, docs/ios/features/feature_app_launch.md, ios/MeasureSDK.xcodeproj/project.pbxproj, ios/MeasureSDK.xcodeproj/xcshareddata/xcschemes/DemoApp.xcscheme, ios/MeasureSDK/AppLaunch/AppLaunchCollector.swift, ios/MeasureSDK/AppLaunch/AppLaunchEvents.swift, ios/MeasureSDK/AppLaunch/LaunchCallbacks.swift, ios/MeasureSDK/AppLaunch/LaunchTracker.swift, ios/MeasureSDK/CoreData/Entities/EventEntity.swift, ios/MeasureSDK/CoreData/EventStore.swift, ios/MeasureSDK/Events/EventProcessor.swift, ios/MeasureSDK/Events/EventType.swift, ios/MeasureSDK/Exporter/EventSerializer.swift, ios/MeasureSDK/MeasureInitializer.swift, ios/MeasureSDK/MeasureInternal.swift, ios/MeasureSDK/Utils/Constants.swift, ios/MeasureSDK/Utils/SysCtl.swift, ios/MeasureSDK/Utils/UserDefaultStorage.swift, ios/MeasureSDK/XCDataModel/MeasureModel.xcdatamodeld/MeasureModel.xcdatamodel/contents, ios/MeasureSDKTests/Exporter/EventSerializerTests.swift, ios/MeasureSDKTests/Helper/TestDataGenerator.swift, ios/MeasureSDKTests/Mocks/MockSysCtl.swift, ios/MeasureSDKTests/Mocks/MockUserDefaultStorage.swift, ios/MeasureSDKTests/Performance/MemoryUsageCollectorTests.swift, ios/MeasureUITests/LaunchCollectorTests.swift, ios/TestApp/AppDelegate.swift, ios/TestApp/MockMeasureInitializer.swift
Collect and export launch related data.
- Cold launch: In iOS, a launch is considered a cold launch if the app is launched for the first time since the device has been rebooted.
- Warm launch: Every subsequent launch after the reboot is deemed as a warm launch.
- Hot launch: When an app moved from background to foreground, its considered a hot launch.
Closes #1527
=> chore(ios): add launch event tracking

frontend/dashboard/app/components/dropdown_select.tsx
Removes cursor:pointer style applied to checkbox container in dropdown select component
=> chore(frontend): remove cursor pointer style

frontend/dashboard/app/components/trace_viz.tsx
Retains overflowing span name bg color
Fixes #1596
=> fix(frontend): retain overflowing span name bg color

backend/api/span/span.go
Handles checkpoint parsing in GetTrace
Fixes #1597, #1594
=> fix(backend): handle checkpoint parsing in GetTrace

frontend/dashboard/app/components/dropdown_select.tsx
Adjusts dropdown select popup position & width
Closes #1608
=> chore(frontend): adjust dropdown select popup position & width

frontend/dashboard/app/components/session_replay_event_details.tsx
Improves user def attrs spacing in session timeline
Closes #1615
=> chore(frontend): improve user def attrs spacing

self-host/session-data/config.toml.example
This PR updates the `self-host/session-data/config.toml.example` file with latest and accurate instructions.
- fixes #1630
=> chore(backend): update sessionator example config

frontend/dashboard/app/api/api_calls.ts
Checks onboarding status after filters api call
Fixes #1638
=> fix(frontend): check onboarding status after filters api call

frontend/dashboard/app/components/filters.tsx
Adds missing span status clearance on filters api call failure
=> chore(frontend): clear span statuses in filters

backend/api/measure/app.go, backend/api/span/span.go, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/session_replay.tsx, frontend/dashboard/app/components/session_replay_event_cell.tsx, frontend/dashboard/app/components/session_replay_event_details.tsx
Shows traces in session timeline
https://github.com/user-attachments/assets/a5bc79ff-f98b-4671-a28e-4ca16e1ba575
Closes #1598
=> feat(backend): show traces in session timeline

backend/api/measure/session.go, backend/api/session/match.go
Adds session id to free text search
Fixes #1645
=> fix(backend): add session id to free text search

self-host/session-data/sh.measure.sample/0.9.0-SNAPSHOT.debug/394f892a-839d-43c2-a0eb-34e9d5cf834d.json
The sample session contains largest and smallest numbers that can be represented by different types on the JVM. All sent as numbers instead of string.
References #1620
=> chore(backend): update user defined attributes in sample session

backend/api/measure/event.go
This PR sends additional details in the response of PUT `/events` API about current and previous event request when ingestion failure happens due to conflict.
- fixes #1682
=> fix(backend): log extra info during ingestion failure

backend/api/event/userdefattr.go
This PR removes a couple of unneeded log lines.
=> chore(backend): remove unneeded log lines

frontend/dashboard/app/api/api_calls.ts
Removes "|| null" from empty metrics sample
=> chore(frontend): remove "|| null" from empty metrics sample

backend/api/measure/auth.go
Logs email to stdout instead of sending to waitlist
Closes #1648
=> chore(backend): log email instead of sending to waitlist

docs/ios/README.md, docs/ios/features/feature_network_changes.md, ios/MeasureSDK.xcodeproj/project.pbxproj, ios/MeasureSDK/CoreData/Entities/EventEntity.swift, ios/MeasureSDK/CoreData/EventStore.swift, ios/MeasureSDK/Events/EventType.swift, ios/MeasureSDK/Exporter/EventSerializer.swift, ios/MeasureSDK/MeasureInitializer.swift, ios/MeasureSDK/MeasureInternal.swift, ios/MeasureSDK/NetworkChange/NetworkChangeCallback.swift, ios/MeasureSDK/NetworkChange/NetworkChangeCollector.swift, ios/MeasureSDK/NetworkChange/NetworkChangeData.swift, ios/MeasureSDK/NetworkChange/NetworkChangeDetector.swift, ios/MeasureSDK/XCDataModel/MeasureModel.xcdatamodeld/MeasureModel.xcdatamodel/contents
Track and export network change events.
Closes #1578
=> chore(ios): track and export network change events

docs/hosting/README.md
This PR addresses the high CPU consumption of ClickHouse under a FAQs section.
- fixes #1722
=> docs(backend): address clickhouse high cpu usage

ios/MeasureSDK.xcodeproj/project.pbxproj, ios/MeasureSDK/Gestures/GestureCollector.swift, ios/MeasureSDK/Gestures/GestureDetector.swift, ios/MeasureSDK/Gestures/GestureEvents.swift, ios/MeasureSDK/Http/HttpData.swift, ios/MeasureSDK/Http/NetworkInterceptorProtocol.swift, ios/MeasureSDK/Http/URLSessionTaskInterceptor.swift, ios/MeasureSDK/Performance/CpuUsageCollector.swift, ios/MeasureSDK/Performance/MemoryUsageCollector.swift, ios/MeasureSDKTests/Performance/CpuUsageCollectorTests.swift, ios/MeasureSDKTests/Performance/MemoryUsageCollectorTests.swift
Bug fixes
Fixes #1521 
Fixes #1700
=> iOS bug fixes

frontend/dashboard/app/components/filters.tsx
Set default session type to All
Fixes #1745
=> fix(frontend): set default session type to All

frontend/dashboard/app/components/dropdown_select.tsx
Adds "None" button to multi-selector within the filter's dropdown. Deselects all values
Closes #1691
Relates to #1692
=> feat(frontend): none selection option in filters dropdown

frontend/dashboard/app/components/dropdown_select.tsx
Removes "None" for app version selection in dropdown select
Closes #1756
=> chore(frontend): remove "None" for app version selection

frontend/dashboard/app/components/session_replay_event_cell.tsx
Updates iOS lifecycle events display name in session timeline
Closes #1751
=> chore(frontend): update iOS lifecycle events display name

self-host/sessionator/go.mod
This PR tidies up sessionator's `go.mod` file. Changes are minimal.
=> chore(backend): tidy sessionator `go.mod`

backend/api/filter/appfilter.go, backend/api/measure/event.go, backend/api/span/span.go, backend/cleanup/cleanup/cleanup.go, frontend/dashboard/app/[teamId]/traces/page.tsx, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/trace_viz.tsx, frontend/dashboard/app/components/user_def_attr_selector.tsx, self-host/clickhouse/20250204070350_alter_spans_table.sql, self-host/clickhouse/20250204070357_create_span_user_def_attrs.sql, self-host/clickhouse/20250204070548_create_span_user_def_attrs_mv.sql, self-host/clickhouse/schema.sql, self-host/session-data/sh.measure.sample/0.9.0-SNAPSHOT.debug/394f892a-839d-43c2-a0eb-34e9d5cf834d.json
Add user defined attrs to spans
Closes #1740
=> feat(backend): add user defined attrs to spans

frontend/dashboard/app/[teamId]/bug_reports/[appId]/[bugReportId]/page.tsx
Renames button to "Close/Re-Open Bug Report"
Closes #1824
=> feat(frontend): rename button to "Close/Re-Open Bug Report"

frontend/dashboard/app/[teamId]/bug_reports/[appId]/[bugReportId]/page.tsx
Matches bug report attr display style with others
Closes #1826
=> feat(frontend): match bug report attr display style with others

frontend/dashboard/app/components/session_replay.tsx
Handles no events selected case in session timeline
Fixes #1834
=> fix(frontend): handle no events selected case in session timeline

backend/cleanup/cleanup/cleanup.go
Cleans up stale bug reports
Closes #1838
=> chore(backend): cleanup stale bug reports

.github/workflows/ios.yml, ios/MeasureSDK.xcodeproj/project.pbxproj, ios/MeasureSDK.xcodeproj/xcshareddata/xcschemes/MeasureSDK.xcscheme, ios/MeasureSDK.xcodeproj/xcshareddata/xcschemes/TestApp.xcscheme, ios/Sources/Tests/MeasureSDKTests/Exporter/HeartbeatTests.swift
Run lint checks and unit test for iOS.
Closes #1808
=> ci(ios): run lint checks

frontend/dashboard/app/layout.tsx, frontend/dashboard/tailwind.config.ts
Renames font variables
Closes #1843
=> chore(frontend): rename font variables

frontend/dashboard/app/[teamId]/bug_reports/page.tsx
Adjusts bug report table text sizes
Closes #1814
=> feat(frontend): adjust bug report table text sizes

frontend/dashboard/app/[teamId]/bug_reports/[appId]/[bugReportId]/page.tsx
Updates bug report details desc text size
Closes #1854
=> feat(frontend): update bug report details desc text size

frontend/dashboard/app/components/session_timeline_event_details.tsx
Refactors details link fetch in session timeline event details
Closes #1837
=> chore(frontend): refactor details link fetch in session timeline event details

android/measure/api/measure.api, android/measure/src/main/java/sh/measure/android/exporter/NetworkPackets.kt, android/measure/src/main/java/sh/measure/android/storage/Database.kt, android/measure/src/main/java/sh/measure/android/storage/DbConstants.kt, android/measure/src/main/java/sh/measure/android/storage/Entities.kt, android/measure/src/main/java/sh/measure/android/storage/SpanDataExtenstions.kt, android/measure/src/main/java/sh/measure/android/tracing/InternalSpan.kt, android/measure/src/main/java/sh/measure/android/tracing/InvalidSpan.kt, android/measure/src/main/java/sh/measure/android/tracing/MsrSpan.kt, android/measure/src/main/java/sh/measure/android/tracing/Span.kt, android/measure/src/main/java/sh/measure/android/tracing/SpanData.kt, android/measure/src/main/java/sh/measure/android/tracing/SpanProcessor.kt, android/measure/src/test/java/sh/measure/android/exporter/MultipartDataFactoryTest.kt, android/measure/src/test/java/sh/measure/android/fakes/TestData.kt, android/measure/src/test/java/sh/measure/android/tracing/MsrSpanTest.kt, android/sample/src/main/java/sh/measure/sample/ExceptionDemoActivity.kt, docs/android/features/feature_performance_tracing.md
Allow user defined attributes with spans
closes #1792
=> feat(android): add attributes to spans

MeasureSDK.podspec, ios/CHANGELOG.md, ios/README.md
=> chore(ios): prepare sdk release 0.0.1-rc1

docs/api/sdk/README.md
=> Update API schema for exceptions to support iOS crash reporting

frontend/dashboard/app/[teamId]/apps/page.tsx, frontend/dashboard/app/[teamId]/bug_reports/page.tsx, frontend/dashboard/app/[teamId]/overview/page.tsx, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/[teamId]/traces/page.tsx, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/components/exceptions_overview.tsx, frontend/dashboard/app/components/filters.tsx
Refactors FiltersApiType to FilterSource
Closes #1812
=> chore(frontend): refactor FiltersApiType to FilterSource

ios/Sources/MeasureSDK/Swift/CrashReporter/CrashDataFormatter.swift
fix `in_app` generation logic
Fixes #1882
=> fix(ios): update in_app generation logic

.github/workflows/changelog.yml, cliff.toml
Update to `orhun/git-cliff-action` action to v4 and updated changelog generation settings.
fixes #1892
=> chore(backend): update ci changelog

docs/ios/README.md, docs/ios/features/feature_network_monitoring.md, ios/MeasureSDK.xcodeproj/project.pbxproj, ios/PublicApi/MeasureSDK.swiftinterface, ios/Sources/MeasureSDK/Swift/Http/MsrNetworkInterceptor.swift, ios/Sources/MeasureSDK/Swift/Http/URLSessionTaskInterceptor.swift
Rename `NetworkInterceptor` to `MsrNetworkInterceptor`
Closes #1901
=> refactor(ios): rename NetworkInterceptor to MsrNetworkInterceptor

backend/api/symbolicator/symbolicator.go
This PR fixes an issue where for some ANR's its type would not get de-obfuscated.
- fixes #1940
=> fix(backend): anr exception type was not symbolicated

ios/Scripts/upload_dsyms.sh
Log appropriate error messages if upload dsym script fails
Closes #1973
=> chore(ios): log error messages when upload dsym script fails

self-host/migrations/v0.6.x-data-backfills.sh
This PR fixes a couple of issues in v0.6.x data backfill script.
=> fix(backend): incorrect data backfill script

Measure.podspec, docs/ios/README.md, ios/CHANGELOG.md, ios/Sources/MeasureSDK/Swift/FrameworkInfo.swift
Prepare iOS SDK release 0.1.0.
=> chore(ios): prepare sdk release 0.1.0

Measure.podspec, docs/ios/README.md, ios/CHANGELOG.md, ios/Sources/MeasureSDK/Swift/FrameworkInfo.swift
Reverts measure-sh/measure#1987
=> Revert "chore(ios): prepare sdk release 0.1.0"

android/CHANGELOG.md, android/gradle.properties, android/gradle/libs.versions.toml, docs/android/README.md
Prepare Android SDK release 0.10.0
=> chore(android): prepare android SDK release 0.10.0

docs/ios/README.md, measure-sh.podspec
Update podspec name from `Measure` to `measure-sh`
Closes #1996
=> chore(ios): update pod name to measure-sh

ios/RELEASE.md, ios/Scripts/release.sh
- Release scripts updated
- RELEASE.md updated
Closes #1997
=> chore(ios): update release script

README.md
Updates README with bug reports feature
Closes #1816
=> docs: update README with bug reports feature

frontend/dashboard/app/page.tsx
Updates iOS availability on landing page
Closes #2002
=> feat(frontend): update iOS availability on landing page

README.md
Updates iOS availability in README
Closes #2013
=> docs: update iOS availability in README

README.md
Updates bug reports feature video from mov to webm
Closes #2014
=> docs: update bug reports feature video from mov to webm

ios/Sources/MeasureSDK/Swift/CoreData/Entities/EventEntity.swift, ios/Sources/MeasureSDK/Swift/Events/Event.swift, ios/Sources/MeasureSDK/Swift/Exception/StackFrame.swift, ios/Sources/MeasureSDK/Swift/Exporter/EventSerializer.swift, ios/Sources/MeasureSDK/Swift/Exporter/HttpClient.swift, ios/Sources/MeasureSDK/Swift/Exporter/HttpModels.swift, ios/Tests/MeasureSDKTests/CrashReporter/CrashReports/abort.json, ios/Tests/MeasureSDKTests/CrashReporter/CrashReports/backgroundThreadException.json, ios/Tests/MeasureSDKTests/Event/EventProcessorTests.swift, ios/Tests/MeasureSDKTests/Exporter/EventSerializerTests.swift, ios/Tests/MeasureSDKTests/Exporter/HttpClientTests.swift
Use `JSONEncoder` to serialise events instead of string concatination
Closes #1637
=> chore(ios): update json encoding logic

android/measure/src/test/java/sh/measure/android/storage/DbMigrationsTest.kt, android/measure/src/test/java/sh/measure/android/storage/TestDatabaseHelper.kt, android/measure/src/test/resources/schemas/schema_v1.sql, android/measure/src/test/resources/schemas/schema_v2.sql, android/measure/src/test/resources/schemas/schema_v3.sql
- Write a helper class which can create a database from a given db schema
- Add tests for existing database migrations
closes #2008
=> chore(android): add db migration tests

ios/.swiftlint.yml, ios/Sources/MeasureSDK/Swift/Config/MeasureConfig.swift, ios/Sources/MeasureSDK/Swift/CoreData/CoreDataEntities/BatchOb+CoreDataProperties.swift, ios/Sources/MeasureSDK/Swift/CoreData/CoreDataEntities/EventOb+CoreDataProperties.swift, ios/Sources/MeasureSDK/Swift/CoreData/CoreDataEntities/SessionOb+CoreDataProperties.swift, ios/Sources/MeasureSDK/Swift/CoreData/EventStore.swift, ios/Sources/MeasureSDK/Swift/CrashReporter/CrashDataFormatter.swift, ios/Sources/MeasureSDK/Swift/Exporter/EventSerializer.swift, ios/Sources/MeasureSDK/Swift/Http/URLSessionTaskInterceptor.swift, ios/Sources/MeasureSDK/Swift/MeasureInternal.swift, ios/Sources/MeasureSDK/Swift/SessionManager.swift, ios/Sources/MeasureSDK/Swift/Utils/AppVersionInfo.swift, ios/Sources/MeasureSDK/Swift/Utils/SysCtl.swift, ios/Tests/MeasureSDKTests/CrashReporter/CrashDataFormatterTests.swift, ios/Tests/MeasureSDKTests/Exporter/EventSerializerTests.swift, ios/Tests/MeasureSDKTests/Exporter/HttpClientTests.swift, ios/Tests/MeasureSDKTests/Http/HttpEventValidatorTests.swift, ios/Tests/MeasureSDKTests/Mocks/MockAppVersionInfo.swift, ios/Tests/MeasureSDKTests/Mocks/MockMeasureInitializer.swift, ios/Tests/MeasureSDKTests/Mocks/MockUserDefaultStorage.swift
Please add a summary of the changes
References #2026
=> chore(ios): update swiftlint

frontend/dashboard/__tests__/pages/bug_reports_overview_test.tsx, frontend/dashboard/__tests__/pages/exception_details_test.tsx, frontend/dashboard/__tests__/pages/exceptions_overview_test.tsx, frontend/dashboard/__tests__/pages/overview_test.tsx, frontend/dashboard/__tests__/pages/sessions_overview_test.tsx, frontend/dashboard/__tests__/pages/traces_overview_test.tsx, frontend/dashboard/app/[teamId]/alerts/page.tsx, frontend/dashboard/app/[teamId]/apps/page.tsx, frontend/dashboard/app/[teamId]/bug_reports/page.tsx, frontend/dashboard/app/[teamId]/layout.tsx, frontend/dashboard/app/[teamId]/overview/page.tsx, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/[teamId]/traces/page.tsx, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/create_app.tsx, frontend/dashboard/app/components/dropdown_select.tsx, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/components/exceptions_overview.tsx, frontend/dashboard/app/components/filters.tsx, frontend/dashboard/app/components/journey.tsx, frontend/dashboard/app/components/user_def_attr_selector.tsx, frontend/dashboard/jest.config.ts, frontend/dashboard/next.config.js, frontend/dashboard/package-lock.json, frontend/dashboard/package.json
Saves page states using urls
Closes #1926
=> chore(frontend): save page state using urls

frontend/dashboard/app/[teamId]/team/page.tsx
Improves teams error UI on change role & remove member errors
Fixes #2070
=> fix(frontend): improve teams error UI on change role & remove member errors

backend/api/measure/team.go
Prevents removal or role change of member in their default team
Fixes #2067
=> fix(backend): prevent removal/role change of member in their default team

flutter/measure_flutter/example/android/app/build.gradle, flutter/measure_flutter/example/android/app/src/main/AndroidManifest.xml, flutter/measure_flutter/example/android/app/src/main/kotlin/sh/measure/android/flutter/MainActivity.kt, flutter/measure_flutter/example/android/app/src/main/kotlin/sh/measure/android/flutter/SampleApp.kt, flutter/measure_flutter/example/ios/Runner.xcodeproj/project.pbxproj
=> chore(flutter): rename sample app identifiers

frontend/dashboard/app/[teamId]/bug_reports/page.tsx, frontend/dashboard/app/[teamId]/overview/page.tsx, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/[teamId]/traces/page.tsx, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/components/exceptions_overview.tsx
Updates filters on ready state change
Fixes #2113
=> fix(frontend): update filters on ready state change

frontend/dashboard/app/auth/login/google-sign-in.tsx, frontend/dashboard/app/auth/login/page.tsx
Moves gsi client script inside google-sign-in component
=> chore(frontend): move gsi client script inside google-sign-in component

frontend/dashboard/app/layout.tsx
Updates social preview links description
=> chore(frontend): update social preview links description

docs/api/sdk/README.md
This PR updates the SDK API documentation to primarily document the `warm_launch` event properties accurately and additionally makes the Markdown formatting consistent throughout.
- fixes #2134
=> Update and format SDK API documentation

docs/hosting/README.md
This PR improves the self host guide based on learnings from issues faced by users.
- fixes #2138
=> docs(backend): update self host guide

docs/api/sdk/README.md
This PR carries out minor formatting changes to SDK API documentation page.
=> docs: format sdk api docs

flutter/measure_flutter/example/lib/main.dart, flutter/measure_flutter/lib/measure.dart, flutter/measure_flutter/lib/src/exception/exception_collector.dart, flutter/measure_flutter/lib/src/exception/exception_factory.dart, flutter/measure_flutter/lib/src/measure_interface.dart, flutter/measure_flutter/lib/src/measure_internal.dart, flutter/measure_flutter/test/exception/exception_collector_test.dart, flutter/measure_flutter/test/measure_test.dart
- Improve API to start the SDK
- Configure error handlers automatically
- Rename IMeasure to MeasureApi
- Expose trackHandledError as public method
Closes #2151
=> chore(flutter): improve initialization and error tracking

frontend/dashboard/app/components/button.tsx, frontend/dashboard/app/components/team_switcher.tsx, frontend/dashboard/app/components/user_avatar.tsx, frontend/dashboard/app/globals.css, frontend/dashboard/tailwind.config.ts
Uses Button component in sidebar
Closes #2156
=> chore(frontend): use Button component in sidebar

frontend/dashboard/app/components/dropdown_select.tsx, frontend/dashboard/app/components/user_def_attr_selector.tsx
Shows filters focus ring only on keyboard nav
=> chore(frontend): show filters focus ring only on keyboard nav

frontend/dashboard/__tests__/components/__snapshots__/accordion_test.tsx.snap, frontend/dashboard/__tests__/components/__snapshots__/alert_dialog_modal_test.tsx.snap, frontend/dashboard/__tests__/components/__snapshots__/paginator_test.tsx.snap, frontend/dashboard/app/[teamId]/alerts/page.tsx, frontend/dashboard/app/[teamId]/apps/page.tsx, frontend/dashboard/app/[teamId]/bug_reports/[appId]/[bugReportId]/page.tsx, frontend/dashboard/app/[teamId]/team/page.tsx, frontend/dashboard/app/[teamId]/traces/[appId]/[traceId]/page.tsx, frontend/dashboard/app/auth/login/github-sign-in.tsx, frontend/dashboard/app/auth/login/google-sign-in.tsx, frontend/dashboard/app/components/accordion.tsx, frontend/dashboard/app/components/alert_dialog_modal.tsx, frontend/dashboard/app/components/copy_ai_context.tsx, frontend/dashboard/app/components/create_app.tsx, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/components/journey.tsx, frontend/dashboard/app/components/landing_header.tsx, frontend/dashboard/app/components/paginator.tsx, frontend/dashboard/app/components/session_timeline_event_cell.tsx, frontend/dashboard/app/components/session_timeline_event_details.tsx, frontend/dashboard/app/components/tab_select.tsx, frontend/dashboard/app/components/team_switcher.tsx, frontend/dashboard/app/components/trace_viz.tsx, frontend/dashboard/app/components/user_avatar.tsx, frontend/dashboard/app/global-error.tsx, frontend/dashboard/app/not-found.tsx, frontend/dashboard/app/page.tsx
Standardises buttons, links, inputs using Button component and standard styles
Closes #2164
=> chore(frontend): standardise buttons, links, inputs using Button component and standard styles

frontend/dashboard/app/globals.css
Fixes sidebar colour
Closes #2171
=> fix(frontend): fix sidebar colour

frontend/dashboard/app/[teamId]/team/page.tsx
Updates member roles after role change
Fixes #2175
=> fix(frontend): update member roles after role change

frontend/dashboard/app/[teamId]/bug_reports/page.tsx, frontend/dashboard/app/[teamId]/overview/page.tsx, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/[teamId]/traces/page.tsx, frontend/dashboard/app/[teamId]/usage/page.tsx, frontend/dashboard/app/components/bug_reports_overview_plot.tsx, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/components/exceptions_details_plot.tsx, frontend/dashboard/app/components/exceptions_distribution_plot.tsx, frontend/dashboard/app/components/exceptions_overview.tsx, frontend/dashboard/app/components/exceptions_overview_plot.tsx, frontend/dashboard/app/components/journey.tsx, frontend/dashboard/app/components/session_timeline.tsx, frontend/dashboard/app/components/sessions_overview_plot.tsx, frontend/dashboard/app/components/span_metrics_plot.tsx
Updates charts UIs
- Removes borders
- Adjusts spacing
- Improves points appearances
- Makes tooltips rounded
Closes #2177
=> feat(frontend): update charts UIs

frontend/dashboard/app/[teamId]/layout.tsx
Fixes sidebar inset padding
Fixes #2218
=> fix(frontend): fix sidebar inset padding

frontend/dashboard/app/[teamId]/apps/page.tsx, frontend/dashboard/app/[teamId]/team/page.tsx, frontend/dashboard/app/utils/use_toast.tsx
closes #2223
Updates positive & negative toast variants
Closes #2223
=> chore(frontend): update postive & negative toast variants

frontend/dashboard/app/[teamId]/bug_reports/[appId]/[bugReportId]/page.tsx, frontend/dashboard/app/components/copy_ai_context.tsx, frontend/dashboard/app/components/create_app.tsx
Adds toasts on:
- Bug report close/re-open
- Copy AI context
- Copy API key in create app
Closes #2219, Closes #2220, Closes #2221
=> chore(frontend): add toasts

frontend/dashboard/app/[teamId]/team/page.tsx
Updates teams page UI:
- Updates tables to new style
- Improves section headings and separators
Closes #2210
=> chore(frontend): update teams page UI

docs/ios/README.md, ios/CHANGELOG.md, ios/Sources/MeasureSDK/Swift/FrameworkInfo.swift, measure-sh.podspec
=> chore(ios): prepare sdk release 0.3.0

frontend/dashboard/app/components/loading_spinner.tsx
Reduces loading spinner size
Closes #2238
=> chore(frontend): reduce loading spinner size

frontend/dashboard/app/[teamId]/apps/page.tsx
Updates apps page ui with better section differentiation
Closes #2228
=> chore(frontend): update apps page ui with better section differentiation

backend/api/measure/team.go, docs/api/dashboard/README.md
This PR updates the GET `/teams/:id/authz` API to always sort the members list in the order membership appearance to make the order predictable.
- fixes #2242
=> fix(backend): members were not ordered in a predictable manner

frontend/dashboard/app/[teamId]/apps/page.tsx, frontend/dashboard/app/components/create_app.tsx
Updates integration guide link
Closes #2249
=> chore(frontend): update integration guide link

frontend/dashboard/app/[teamId]/alerts/page.tsx, frontend/dashboard/app/[teamId]/team/page.tsx, frontend/dashboard/app/[teamId]/usage/page.tsx, frontend/dashboard/app/components/team_switcher.tsx
Uses loading spinners instead of loading text
Closes #2260
=> chore(frontend): use loading spinner instead of loading text

frontend/dashboard/app/[teamId]/team/page.tsx, frontend/dashboard/app/components/create_team.tsx
Moves team creation to dialog
Closes #2200
=> chore(frontend): move team creation to dialog

frontend/dashboard/app/[teamId]/team/page.tsx, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/create_team.tsx
Selects new team on team create
Closes #2277
=> chore(frontend): select new team on team create

docs/sdk-integration-guide.md, ios/CHANGELOG.md, ios/Sources/MeasureSDK/Swift/FrameworkInfo.swift, measure-sh.podspec
=> chore(ios): prepare sdk release 0.4.0

ios/MeasureSDK.xcodeproj/project.pbxproj, ios/Sources/MeasureSDK/Swift/Attribute/Attribute.swift, ios/Sources/MeasureSDK/Swift/Attribute/NetworkStateAttributeProcessor.swift, ios/Sources/MeasureSDK/Swift/Attribute/UserAttributeProcessor.swift, ios/Sources/MeasureSDK/Swift/Events/CustomEventCollector.swift, ios/Sources/MeasureSDK/Swift/Events/InternalSignalCollector.swift, ios/Sources/MeasureSDK/Swift/Events/SignalProcessor.swift, ios/Sources/MeasureSDK/Swift/MeasureInitializer.swift, ios/Sources/MeasureSDK/Swift/Utils/MeasureDispatchQueue.swift, ios/Tests/MeasureSDKTests/Attribute/UserAttributeProcessorTests.swift, ios/Tests/MeasureSDKTests/Event/EventProcessorTests.swift, ios/Tests/MeasureSDKTests/Exporter/ExporterTests.swift, ios/Tests/MeasureSDKTests/Mocks/MockMeasureDispatchQueue.swift, ios/Tests/MeasureSDKTests/Mocks/MockMeasureInitializer.swift, ios/Tests/MeasureSDKTests/Mocks/MockMotionManager.swift
Attribute processor encounters race condition. This PR make the attribute processor thread safe.
Fixes #2350
=> fix(ios): make attribute processor thread safe

ios/DemoApp/AppDelegate.swift, ios/MeasureSDK.xcodeproj/project.pbxproj, ios/PublicApi/Measure.swiftinterface, ios/Scripts/upload_dsym_build_phases.sh, ios/Scripts/upload_dsyms.sh, ios/Sources/MeasureSDK/Swift/Config/BaseConfigProvider.swift, ios/Sources/MeasureSDK/Swift/Config/Config.swift, ios/Sources/MeasureSDK/Swift/Config/DefaultConfig.swift, ios/Sources/MeasureSDK/Swift/Config/InternalConfig.swift, ios/Sources/MeasureSDK/Swift/Config/MeasureConfig.swift, ios/Sources/MeasureSDK/Swift/Config/MsrRequestHeadersProvider.swift, ios/Sources/MeasureSDK/Swift/Exporter/HttpClient.swift, ios/Sources/MeasureSDK/Swift/MeasureInitializer.swift, ios/Tests/MeasureSDKTests/Exporter/HttpClientTests.swift, ios/Tests/MeasureSDKTests/Mocks/MockConfigProvider.swift
The PR contains below 2 feature:
- Option to add custom header Measure API call using MsrRequestHeadersProvider.
- Option to add custom header Measure build api.
Closes #2347
=> feat(ios): add support for custom header

android/measure/src/main/java/sh/measure/android/events/InternalSignalCollector.kt, android/measure/src/main/java/sh/measure/android/gestures/GestureEvents.kt, android/measure/src/main/java/sh/measure/android/layoutinspector/LayoutInspector.kt, flutter/.dart_tool/package_config.json, flutter/packages/measure_dio/test/fake_measure.dart, flutter/packages/measure_flutter/lib/measure.dart, flutter/packages/measure_flutter/lib/src/events/event_type.dart, flutter/packages/measure_flutter/lib/src/gestures/click_data.dart, flutter/packages/measure_flutter/lib/src/gestures/click_data.g.dart, flutter/packages/measure_flutter/lib/src/gestures/detected_element.dart, flutter/packages/measure_flutter/lib/src/gestures/gesture_collector.dart, flutter/packages/measure_flutter/lib/src/gestures/long_click_data.dart, flutter/packages/measure_flutter/lib/src/gestures/long_click_data.g.dart, flutter/packages/measure_flutter/lib/src/gestures/msr_gesture_detector.dart, flutter/packages/measure_flutter/lib/src/gestures/scroll_data.dart, flutter/packages/measure_flutter/lib/src/gestures/scroll_data.g.dart, flutter/packages/measure_flutter/lib/src/gestures/scroll_direction.dart, flutter/packages/measure_flutter/lib/src/measure_api.dart, flutter/packages/measure_flutter/lib/src/measure_initializer.dart, flutter/packages/measure_flutter/lib/src/measure_internal.dart, flutter/packages/measure_flutter/lib/src/measure_widget.dart, flutter/packages/measure_flutter/test/gestures/msr_gesture_detector_test.dart, flutter/packages/measure_flutter/test/utils/fake_measure.dart, ios/Sources/MeasureSDK/Swift/Events/InternalSignalCollector.swift, ios/Sources/MeasureSDK/Swift/Gestures/GestureEvents.swift, ios/Sources/MeasureSDK/Swift/Gestures/GestureTargetFinder.swift
=> feat(flutter): track gestures

frontend/dashboard/dockerfile.prod, self-host/compose.prod.yml
This PR modifies the compose.prod.yml file and introduces the `API_BASE_URL` environment variable with a suitable value to make the dashboard compose build succeed.
- fixes #2409
=> chore(backend): modify production dashboard compose

android/gradle.properties, docs/sdk-integration-guide.md
Prepare Android SDK release 0.11.0
=> chore(android): prepare sdk release 0.11.0

.github/workflows/gradle-plugin-prepare-release.yml, docs/sdk-integration-guide.md
Prepare release Measure Android Gradle Plugin version 0.9.0
References #2286
=> chore(gradle): prepare plugin release 0.9.0

flutter/example/android/app/build.gradle, flutter/packages/measure_flutter/CHANGELOG.md, flutter/packages/measure_flutter/android/build.gradle, flutter/packages/measure_flutter/cliff.toml, flutter/packages/measure_flutter/ios/measure_flutter.podspec
Prepare release `measure_flutter-v0.1.0`
References #2286
=> chore(flutter): prepare measure_flutter-v0.1.0

android/measure/src/main/java/sh/measure/android/config/MeasureConfig.kt, flutter/packages/measure_flutter/lib/src/config/config.dart, flutter/packages/measure_flutter/lib/src/config/config_provider.dart, flutter/packages/measure_flutter/lib/src/config/default_config.dart, flutter/packages/measure_flutter/lib/src/config/measure_config.dart, flutter/packages/measure_flutter/lib/src/config/measure_config.g.dart, flutter/packages/measure_flutter/test/utils/fake_config_provider.dart
- adds a new public config (maxDiskUsageInMb) in Flutter SDK
References #2443
=> feat(flutter): provide configurable storage limits

android/measure/src/main/java/sh/measure/android/events/SignalProcessor.kt
Log every event collected by SDK to logcat if logging is enabled.
Closes #2486
=> chore(android): add event logging

frontend/dashboard/__tests__/pages/bug_reports_overview_test.tsx, frontend/dashboard/__tests__/pages/sessions_overview_test.tsx, frontend/dashboard/__tests__/pages/traces_overview_test.tsx, frontend/dashboard/app/[teamId]/bug_reports/page.tsx, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/[teamId]/traces/page.tsx
Removes "v" prefix from app version
Closes #2497
=> chore(frontend): remove "v" prefix from app version

android/measure/api/measure.api, android/measure/src/main/java/sh/measure/android/Measure.kt, android/measure/src/main/java/sh/measure/android/MeasureInternal.kt, android/measure/src/main/java/sh/measure/android/events/UserTriggeredEventCollector.kt, android/measure/src/test/java/sh/measure/android/events/UserTriggeredEventCollectorImplTest.kt
Updates public API for `trackHandledException` to allow adding attributes.
Closes #2506
=> feat(android): add custom attributes to trackHandledException

flutter/example/android/app/build.gradle, flutter/example/pubspec.lock, flutter/packages/measure_flutter/android/build.gradle, flutter/packages/measure_flutter/example/pubspec.lock, flutter/packages/measure_flutter/lib/measure_flutter.dart, flutter/packages/measure_flutter/lib/src/config/config.dart, flutter/packages/measure_flutter/lib/src/config/config_provider.dart, flutter/packages/measure_flutter/lib/src/config/default_config.dart, flutter/packages/measure_flutter/lib/src/config/internal_config.dart, flutter/packages/measure_flutter/lib/src/measure_initializer.dart, flutter/packages/measure_flutter/lib/src/measure_internal.dart, flutter/packages/measure_flutter/lib/src/method_channel/signal_processor.dart, flutter/packages/measure_flutter/lib/src/navigation/navigation_collector.dart, flutter/packages/measure_flutter/test/method_channel/signal_processor_test.dart, flutter/packages/measure_flutter/test/navigation/navigation_collector_test.dart, flutter/packages/measure_flutter/test/utils/fake_config_provider.dart
- Updates build.gradle files to local snapshot versions of native SDK for development
- Expose new API to track screen view events
- Discard events with invalid user defined attributes
Closes #2521
=> feat(flutter): add custom attributes to trackScreenView

ios/PublicApi/Measure.swiftinterface, ios/Sources/MeasureSDK/Swift/Events/Attachment.swift
Make MsrAttachment properties public.
Fixes #2532
=> fix(ios): make MsrAttachment properties public

android/gradle/libs.versions.toml, android/measure-android-gradle/build.gradle.kts, android/measure/build.gradle.kts
Upgrade maven publish plugin to allow publishing SNAPSHOT versions.
References #2530
=> ci: upgrade maven publish plugin

.github/workflows/android-prepare-release.yml, .github/workflows/gradle-plugin-prepare-release.yml
Add a PAT to create release PRs.
References #1992
=> ci: use PAT for creating release PRs

ios/Sources/MeasureSDK/Swift/Config/Config.swift
add more view controllers to be ignored
Closes #2560
=> chore(ios): add more view controllers to be ignored

ios/Scripts/upload_dsym_manual.sh, ios/Scripts/upload_dsym_xcarchive.sh
Add script to upload dsyms from xcarchive
Closes #2558
=> chore(ios): add script to upload dsyms from xcarchive

docs/features/performance-impact.md
update performance docs
Closes #2604
=> chore(ios): update performance docs

ios/Scripts/upload_dsym_build_phases.sh, ios/Scripts/upload_dsym_manual.sh, ios/Scripts/upload_dsym_xcarchive.sh, ios/Scripts/upload_dsyms.sh
Update upload dyms scripts
Closes #2625
=> chore(ios): update upload dyms scripts

react-native/example/rnExample/android/app/build.gradle, react-native/example/rnExample/android/build.gradle
- Remove unneeded NDK version
- Remove unused `kotlin` and `buildTools` version
=> refactor(rn): refactor build scripts

react-native/android/src/main/java/sh/measure/rn/MeasureModule.kt, react-native/example/rnExample/App.tsx, react-native/ios/MeasureModule.swift
initialize native sdks in main thread
Closes #2669
=> chore(rn): initialize native sdks in main thread

frontend/dashboard/app/components/landing_header.tsx
This PR removes the condition in `landing_header.tsx` file to show a 'Getting Started' button. It'll always show the 'Login' button from now on.
- fixes #2707
=> chore(frontend): always show login button on dashboard homepage
