measure-sh/measure

android/measure/consumer-rules.pro, android/measure/src/androidTest/java/sh/measure/android/TestMeasureInitializer.kt, android/measure/src/main/java/sh/measure/android/Measure.kt, android/measure/src/main/java/sh/measure/android/MeasureInitializer.kt, android/measure/src/main/java/sh/measure/android/MeasureInternal.kt, android/measure/src/main/java/sh/measure/android/okhttp/HttpEventCollector.kt, android/measure/src/main/java/sh/measure/android/okhttp/HttpEventCollectorFactory.kt, android/measure/src/main/java/sh/measure/android/okhttp/OkHttpEventCollector.kt
This commit addresses a crash that occurred when instantiating `OkHttpEventCollectorImpl` without verifying the presence of OkHttp as a runtime dependency. The issue was introduced in #980 when OkHttp was changed to a compile-time dependency.
Changes:
* Implement runtime checks for OkHttp availability before accessing OkHttp-dependent classes
* Add ProGuard rule to preserve ability to check for OkHttp presence
This solution ensures the SDK functions correctly regardless of whether OkHttp is available at runtime.
closes: [#1066](https://github.com/measure-sh/measure/issues/1066)
=> fix(android): resolve crash when OkHttp is not a runtime dependency

.github/workflows/android.yml, android/measure-android-gradle/build.gradle.kts, android/measure-android-gradle/gradle.properties, android/measure/build.gradle.kts
* Updates github action to publish to gradle plugin portal along with maven central
* Updates group ID for gradle plugin to sh.measure instead of sh.measure.android.gradle. This will change the coordinates for maven, but this is the group ID we want to start using from now onwards.
* Enable automatic release to maven central, we would no longer need to press the publish button on the website.
closes #1068
=> chore(android): configure ci to publish to gradle plugin portal and enable automatic releases for maven central

frontend/dashboard/app/auth/login/google-sign-in.tsx, frontend/dashboard/dockerfile, frontend/dashboard/dockerfile.prod, self-host/compose.prod.yml, self-host/compose.yml
This PR reverts the ux mode of Google SignIn to `popup` instead of `redirect` because otherwise Google SignIn fails on production with the following error.
```
GSI_LOGGER]: The given login_uri is not allowed for the given client ID.
```
Verified that Google Signin on iOS (17.6.1) Safari works in popup mode on production.
Also, healthcheck for dashboard service was failing because next.js binds the production server on the `HOSTNAME` environment variable if present. This PR, adds a suitable `HOSTNAME` environment variable for the production dockerfile of dashboard.
=> chore: fix self host and google signin

android/measure-android-gradle/src/main/kotlin/sh/measure/DependencyUtils.kt, android/measure-android-gradle/src/main/kotlin/sh/measure/MeasurePlugin.kt, android/measure-android-gradle/src/main/kotlin/sh/measure/SemVer.kt, android/measure-android-gradle/src/main/kotlin/sh/measure/asm/AsmBytecodeTransformer.kt, android/measure-android-gradle/src/main/kotlin/sh/measure/asm/BytecodeTransformationPipeline.kt, android/measure-android-gradle/src/main/kotlin/sh/measure/asm/BytecodeTransformationPipelineBuilder.kt, android/measure-android-gradle/src/main/kotlin/sh/measure/asm/BytecodeTransformer.kt, android/measure-android-gradle/src/main/kotlin/sh/measure/asm/ModuleInfo.kt, android/measure-android-gradle/src/main/kotlin/sh/measure/asm/NavigationTransformer.kt, android/measure-android-gradle/src/main/kotlin/sh/measure/asm/OkHttpTransformer.kt, android/measure-android-gradle/src/main/kotlin/sh/measure/asm/TransformerParameters.kt, android/measure-android-gradle/src/main/kotlin/sh/measure/asm/VersionAwareVisitor.kt, docs/android/features/feature_navigation_and_lifecycle.md, docs/android/gradle-plugin.md
Bytecode transformation now requires configuring min and max supported versions for the library being transformed. The transformation is applied only when the resolved version lies within the constraints provided. This makes the SDK more robust and reduces the chances of crashes at runtime when changing library versions.
This PR fixes the issues which were present in https://github.com/measure-sh/measure/pull/1053:
* Dependencies declared via BOM or version catalog bundles are now parsed correctly.
* Resolved dependencies are read lazily, ensuring we always have them available when class visitor needs to be created (which is where we make the version check).
=> feat(android): apply bytecode transformation only for supported dependency versions

.github/workflows/android.yml
Use `:measure-gradle-plugin:publish` instead of `publishPluginMavenPublicationToMavenCentralRepository` to ensure the [plugin marker artefact](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers) is also published.
=> chore(android): fix publish command for gradle plugin on CI

frontend/dashboard/app/components/copy_ai_context.tsx, frontend/dashboard/app/components/exceptions_details.tsx
closes #1025
This commit adds a "Copy AI context" button to crash/ANR details page.
This button copies key attributes and stack traces to the clipboard along with a prompt.
The intention is to make it easy for developers
to paste this context into an LLM of their choice and get help in debugging.
Sample context that gets copied:
```
I am trying to fix an exception in my Android app. The details of the exception are as follows: 
App Name: Sample
App version: 1.0
Date & time: Thu, 25 Jul, 2024, 12:14:07:239 PM
Platform: android
Device: Googlesdk_gphone64_arm64
Network type: wifi
STACK TRACES:
Thread: main
Stacktrace:
java.lang.IllegalAccessException: This is a new exception
at sh.measure.sample.ExceptionDemoActivity.onCreate$lambda$0(ExceptionDemoActivity.kt:21)
at …
```
=> feat(frontend): add "Copy AI context" button

docs/hosting/README.md, frontend/dashboard/README.md
Organize and format few commands in the self host guide so that they are easier to copy. Added information around how to choose the correct tag for self hosting and fixed a broken link in dashboard's readme.
=> docs: improve self host guide

backend/api/measure/app.go
fixes #1096
since introducing cleanup service, we can now have exception/anr groups with no events ids.
This commit handles these cases by returning 0 instance count for these groups.
=> fix(backend): handle exception/anr groups with no events

.github/workflows/changelog.yml, .github/workflows/release.yml, cliff.toml, docs/CONTRIBUTING.md
This PR configures the ability to generate changelog automatically in a consistent manner following [conventionalcommits](https://conventionalcommits.org) but tailored for the project's needs using [git-cliff](https://git-cliff.org). Also, update contributing guide to contain the command to create a new release.
=> ci: add changelog generation

.github/workflows/changelog.yml
Trying to push auto generated changelog with a fine-grained Personal Access Token (PAT). This unlocks simplified & unobtrusive changelog generation.
=> ci: update secret for git push of auto generated changelog

backend/api/measure/event.go
Symbolication failure for an event batch would return with an error earlier whereas we want event ingestion to continue even if symbolication fails. This PR makes it so.
Fixes #1016
=> fix(backend): proceed with event ingestion on symbolication failure

ios/MeasureDemo/MeasureDemo/AppDelegate.swift, ios/MeasureDemo/MeasureDemo/MeasureManager.h, ios/MeasureDemo/MeasureDemo/MeasureManager.m, ios/MeasureSDK/MeasureSDK.xcodeproj/project.pbxproj, ios/MeasureSDK/MeasureSDK/Config/ClientInfo.swift, ios/MeasureSDK/MeasureSDK/Measure.swift, ios/MeasureSDK/MeasureSDK/MeasureInitializer.swift
This PR updates the iOS SDK initialisation to accept API-KEY and API-URL as parameters.
SDK initialisation code will look something like this.
```
- Swift:
let config = BaseMeasureConfig()
let clientInfo = ClientInfo(apiKey: "<apiKey>", apiUrl: "<apiUrl>")
Measure.shared.initialize(with: clientInfo, config: config)
- Objective-C:
BaseMeasureConfig *config = [[BaseMeasureConfig alloc] init];
ClientInfo *clientInfo = [[ClientInfo alloc] initWithApiKey:@"<apiKey>" apiUrl:@"<apiUrl>"];
[[Measure shared] initializeWith:clientInfo config:config];
```
Closes #1120
=> Configure API_KEY and API_URL to initialise the SDK

backend/api/group/group.go, backend/api/measure/app.go, backend/api/measure/event.go, backend/cleanup/cleanup/cleanup.go, self-host/postgres/20231228033348_create_unhandled_exception_groups_table.sql, self-host/postgres/20231228044339_create_anr_groups_table.sql
Crash and ANR groups have a list of event ids associated with them which are stored as an array in the 'event_ids' column in Postgres. Postgres fields have a [limit of 1GB](https://www.postgresql.org/docs/current/limits.html) and this list can get quite large in high scale environments.
To improve this situation, this commit:
1. Removes the event_ids column from postgres
2. Fetches event ids of crash + anr groups from clickhouse based on the event's fingeprint
3. Updates the ingest algorithm to no longer append event_ids to crash & anr groups and only update updated_at and first_seen_event timestamps
4. Updates the cleanup service to no longer delete event_ids from postgres on stale event cleanup
Closes #1027
=> chore(backend): remove eventIds array from crash + anr groups

backend/api/measure/app.go
Fixes filters being applied on the wrong statement variable while fetching Crash and ANR groups
=> fix(backend): fix incorrect filter query for crash & anr groups

backend/api/filter/appfilter.go, backend/api/measure/app.go
- App journey attempts to validate versions without checking if any versions are present. This commit adds that missing check.
- App metrics has multiple queries where at least one version is expected to be present. In case no versions are present, this commit assings all versions as selected to achieve the expected behaviour.
Fixes #1157
=> fix(backend): handle no selected versions for app journey & metrics

android/measure/src/androidTest/java/sh/measure/android/TestMeasureInitializer.kt, android/measure/src/main/java/sh/measure/android/MeasureInitializer.kt, android/measure/src/main/java/sh/measure/android/NativeBridge.kt
- Add try-catch blocks to handle potential exceptions when loading the native library
- Catch all exceptions in enableAnrReporting. This is needed to catch any exception thrown if measure-ndk fails to load.
There is no clean way to write a test for this as the native library load cannot be faked easily. The change is tested manually. 
References: #1174
=> fix(android): handle exceptions when loading native library

android/measure/src/main/java/sh/measure/android/applaunch/LaunchTracker.kt
On certain devices we're detecting a warm/hot launch without having the `lastAppVisibleTime` set, which is unusual. This causes a NPE. This PR discards the event and logs an error instead of crashing in such a case.
This PR also adds two more safe checks to LaunchTracker:
1. Removes usage of getValue when accessing maps which can potentially throw.
2. Removes an explicit throw and replaces it with an error log.
#1180
=> fix(android): crash when app visible time isn't available to calculate launch time

android/measure/src/main/java/sh/measure/android/appexit/AppExitCollector.kt, android/measure/src/main/java/sh/measure/android/performance/CpuUsageCollector.kt, android/measure/src/main/java/sh/measure/android/storage/Database.kt
Removes all !! usage from the SDK to make sure we're not forcing any variable to cast as a non-nullable to avoid NPEs.
https://github.com/measure-sh/measure/issues/1180
=> refactor(android): remove usage of double bang operator

self-host/sessionator/README.md, self-host/sessionator/cmd/ingest.go, self-host/sessionator/cmd/rm.go
This PR adds a `--clean-all` flag to clean all old data regardless of app settings in `config.toml`. Running sessionator with this new flag address the mismatching of crash/ANR instances in #1171.
fixes #1171
=> chore(backend): sessionator `--clean-all` flag

backend/api/event/event.go
Fixes formatting of a log line for logging `cold_launch` duration anomalies. The `\n` was not getting printed correctly.
fixes #1181
=> chore(backend): format log line

backend/api/measure/event.go
Event ingestion was failing because of a typo for `low_memory` events.
fixes #1182
=> fix(backend): nil pointer dereference when ingesting `low_memory` events

backend/api/event/event.go, docs/api/sdk/README.md, self-host/clickhouse/20240905133723_alter_events_table.sql
Addresses an issue where for certain events ingestion would fail with a `400 Bad Request` due to integer overflow errors.
- `gesture_click.touch_down_time`
- `gesture_click.touch_up_time`
- `gesture_long_click.touch_down_time`
- `gesture_long_click.touch_up_time`
- `gesture_scroll.touch_down_time`
- `gesture_scroll.touch_up_time`
- `cold_launch.process_start_uptime`
- `cold_launch.process_start_requested_uptime`
- `cold_launch.content_provider_attach_uptime`
- `cold_launch.on_next_draw_uptime`
- `warm_launch.app_visible_uptime`
- `warm_launch.on_next_draw_uptime`
- `hot_launch.app_visible_uptime`
- `hot_launch.on_next_draw_uptime`
- `cpu_usage.interval`
- `memory_usage.interval`
- Fixes #1184
=> Fix ingestion related integer overflow errors

backend/api/go.mod, backend/api/go.sum, backend/api/inet/ipinfo.go, backend/api/inet/ipinfo_test.go, backend/api/measure/event.go
Bogon filtering of IPs during ingestion was still contacting remote IPInfo servers and thus was hitting IPInfo's rate limits thereby failing ingestion. This PR detects bogon IPs locally without depending on any remote servers. The newer implementation looks up country code first and checks for bogon addresses if a valid country code is not found. If IP is not bogon, we set country code as `n/a`.
fixes #1178
=> fix(backend): detect bogon addresses locally

ios/MeasureSDK/MeasureSDK.xcodeproj/project.pbxproj, ios/MeasureSDK/MeasureSDK/Events/Attachment.swift, ios/MeasureSDK/MeasureSDK/Events/AttachmentType.swift, ios/MeasureSDK/MeasureSDK/Events/Event.swift, ios/MeasureSDK/MeasureSDK/Events/EventProcessor.swift, ios/MeasureSDK/MeasureSDK/Events/EventType.swift, ios/MeasureSDK/MeasureSDK/MeasureInitializer.swift, ios/MeasureSDK/MeasureSDK/MeasureInternal.swift, ios/MeasureSDK/MeasureSDKTests/Mocks/MockLogger.swift, ios/MeasureSDK/MeasureSDKTests/Mocks/MockSessionManager.swift, ios/MeasureSDK/MeasureSDKTests/Mocks/MockSystemTime.swift, ios/MeasureSDK/MeasureSDKTests/SessionManagerTests.swift
events processor added to the iOS SDK.
closes #1204 
Tests are currently not added as there is no public api to access events. Tests will be added once EventStore is created. Related issue: #1205
=> add EventProcessor to iOS

backend/api/filter/appfilter.go, backend/api/measure/app.go, backend/api/measure/event.go, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/filters.tsx, frontend/dashboard/app/components/sessions_overview_plot.tsx, frontend/dashboard/app/utils/time_utils.ts
- Show "N/A" for 0 duration
- Fix some sessions show 0 duration even if it has more events
- Add event id target as searchable property
- Placeholder: add all searchable properties
- Show only date in instances plot and not time
- Fix plot sessions calculating first_time_time for session over filtered events instead of whole session
- Fix plot grouping happening on server timezone instead of client time zone
Closes #1209 if not bug fix task
=> feat(backend): improve session explorer

frontend/dashboard/app/components/exceptions_details_plot.tsx, frontend/dashboard/app/components/exceptions_overview_plot.tsx
Use whole integer left axes for crash + anr instances plots instead of having decimals
Fixes #1216
=> fix(frontend): use whole int left axes for crash + anr instances plots

self-host/compose.yml, self-host/sessionator/cmd/ingest.go, self-host/sessionator/cmd/rm.go, self-host/sessionator/cmd/virtual.go, self-host/sessionator/go.mod, self-host/sessionator/go.sum
Equip sessionator to virtualize existing session data events and send multiple request in parallel with the ability to control the ingestion rate.
fixes #1193
=> chore(backend): enable sessionator parallel ingest

backend/api/measure/app.go, backend/api/measure/event.go, frontend/dashboard/app/api/api_calls.ts
Use client timezones for grouping instances in Crash and ANR plots
Fixes #1215
=> fix(backend): use client timezone for plots

backend/api/measure/app.go, backend/api/measure/event.go, frontend/dashboard/__tests__/utils/time_utils.test.ts, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/copy_ai_context.tsx, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/components/exceptions_details_plot.tsx, frontend/dashboard/app/components/exceptions_overview_plot.tsx, frontend/dashboard/app/components/filters.tsx, frontend/dashboard/app/components/session_replay_event_accordion.tsx, frontend/dashboard/app/components/sessions_overview_plot.tsx, frontend/dashboard/app/utils/time_utils.ts
Refactor time utils to have separate functions for human readable datetime, date only and time only
Closes #1223
=> Refactor time utils

android/measure/src/main/java/sh/measure/android/screenshot/ScreenshotCollector.kt
Fixes issue where screenshots on Android 15 were blank. This happened due to incorrect usage of PixelCopy, where instead of using the completion listener the code was assuming `PixelCopy.request` to work synchronously.
This likely broke only in Android 15 after the following PR was merged:
https://android-review.googlesource.com/c/platform/frameworks/base/+/3015073
Manually using an Android 15 emulator.
Fixes #1222
=> fix(android): blank screenshots for Android 15

frontend/dashboard/app/components/dropdown_select.tsx
- Adds 'All' option to multi string dropdown select component
- Adds 'All' and 'Latest' option to multi app version dropdown select component
- Enforces at least 1 selection in both cases
Closes #1161
=> feat(frontend): add 'All', 'Latest' options + 'at least 1' enforcement

frontend/dashboard/app/[teamId]/apps/page.tsx, frontend/dashboard/app/[teamId]/overview/page.tsx, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/components/exceptions_details_plot.tsx, frontend/dashboard/app/components/exceptions_overview.tsx, frontend/dashboard/app/components/exceptions_overview_plot.tsx, frontend/dashboard/app/components/filters.tsx, frontend/dashboard/app/components/journey.tsx, frontend/dashboard/app/components/metrics_overview.tsx, frontend/dashboard/app/components/sessions_overview_plot.tsx
- Uses selected filters instead of passing around expanded parameters
- Renames filter variables for consistency
Closes #1243
=> chore(frontend): use selected filters instead of expanded params

android/measure/src/main/java/sh/measure/android/applaunch/LaunchTracker.kt
Fixes incorrect cold launch attribution, closes #1246.
⚠️ After this PR, users might notice a change in cold/warm launch metric even if they haven't made any changes because the attribution for warm/cold launch has changed.
=> feat(android): report activity launched with saved state as warm launch

frontend/dashboard/app/components/session_replay_event_accordion.tsx
Hide attachment data in session replay event body
Fixes #1257
=> fix(frontend): hide attachment data in session replay event body

android/benchmarks/app/build.gradle.kts, android/benchmarks/benchmark/build.gradle.kts, android/gradle/libs.versions.toml, android/measure-android-gradle/src/functionalTest/kotlin/sh/measure/MeasurePluginTest.kt, android/measure-android-gradle/src/functionalTest/kotlin/sh/measure/fixtures/MeasurePluginFixture.kt, android/measure/build.gradle.kts, android/measure/src/androidTest/java/sh/measure/android/TestMeasureInitializer.kt, android/measure/src/main/java/sh/measure/android/storage/Database.kt, android/measure/src/main/java/sh/measure/android/storage/DbConstants.kt, android/sample/build.gradle.kts
Version updates for compile sdk, target sdk and AGP to latest.
closes #1248
=> chore(android): update sdk version to 35 and agp to 8.6

frontend/dashboard/__tests__/components/__snapshots__/filter_pill_test.tsx.snap, frontend/dashboard/app/components/filter_pill.tsx, frontend/dashboard/app/components/info_circle_app_adoption.tsx, frontend/dashboard/app/components/info_circle_app_size.tsx, frontend/dashboard/app/components/info_circle_app_start_time.tsx, frontend/dashboard/app/components/info_circle_exception_rate.tsx
- Updates tooltip text sizes
- Makes tooltip margins consistent
- Adds raw session data to App Adoption tooltip
Closes #1261
=> feat(frontend): update tooltips

backend/api/measure/auth.go
Tracks email on new user sign in
Closes #1269
=> feat(backend): track email on new user sign in

frontend/dashboard/app/global-error.tsx
Adds custom error page
Closes #1275
=> feat(frontend): add custom error page

backend/api/measure/app.go
For cases when multiple app versions are available, crash/ANR/session overview instance plot was throwing an index of out range error
fixes #1287
=> fix(backend): overview instance plot would not load for some cases

backend/api/go.mod, backend/api/main.go, backend/api/server/middleware.go, backend/api/server/server.go
Capture additional details like error response body, stacktrace for runtime errors and HTTP host and referer values from request in OpenTelemetry traces.
fixes #1163
fixes #1278
=> chore(backend): capture more details in otel traces

backend/api/measure/app.go
- fix a runtime panic in crash/ANR detail instances plot API which happens for cases when an app has multiple versions
fixes #1297
=> fix(backend): crash/anr details instances plot won't load sometimes

frontend/dashboard/app/[teamId]/apps/page.tsx, frontend/dashboard/app/[teamId]/overview/page.tsx, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/components/exceptions_overview.tsx, frontend/dashboard/app/components/filters.tsx
Filters were only considered to be "ready" when filters api is in success status. In pages like apps, we need the option to handle no data and not onboarded ourselves since we need to show app info even when no data is present or app is not onboarded.
Fixes #1296
=> fix(frontend): add option to handle no data & not onboarded in filters

android/measure/consumer-rules.pro
Fragment lifecycle events were not being tracked when r8 was enabled due to a missing ProGuard rule. This PR adds the necessary ProGuard rule to address this issue.
Manually using sample app, on a release build with `minifyEnabled = true` — fragment lifecycle events are tracked.
On an app without `androidx.fragment` dependency — no impact.
closes #1326
=> fix(android): track fragment lifecycle events when r8 is enabled

backend/api/event/attribute.go, self-host/clickhouse/20241015073422_alter_events_table.sql
Increase `attribute.thread_name` upper character limit to 128 from 64 to prevent event validation failures during ingestion.
=> fix(backend): increase thread name character limit

backend/api/event/attribute.go, self-host/clickhouse/20241015075419_alter_events_table.sql
Increase `attribute.app_version` upper character limit to 64 from 32 to prevent event validation failures during ingestion.
=> fix(backend): increase app version character limit

backend/api/event/event.go
For some exception and ANRs, frames could be zero. This may happen (we suspect) when crashes/ANRs originated because of Out of Memory situations.
This patch handles such cases so that the server doesn't throw runtime panics.
- fixes #1337
=> fix(backend): occasional runtime panic during ingestion

frontend/dashboard/app/auth/login/page.tsx
If user goes to `/auth/login` and is logged in already, we now take them directly to dashboard
https://github.com/user-attachments/assets/ec9e03dd-2e62-4f16-98d8-944a31bccc84
Closes #1354
=> chore(frontend): go directly to dashboard if logged in

frontend/dashboard/app/components/exceptions_overview.tsx
Handle empty file/method name in exceptions overview and details components
Fixes #1346
=> fix(frontend): handle empty file/method name

frontend/dashboard/__tests__/components/__snapshots__/filter_pill_test.tsx.snap, frontend/dashboard/app/[teamId]/layout.tsx, frontend/dashboard/app/components/filter_pill.tsx, frontend/dashboard/app/components/filters.tsx
Fixes nav aside scroll on detail content exceeding screen area
Fixes #1360
=> fix(frontend): fix nav aside scroll on detail content exceeding screen area

frontend/dashboard/app/components/dropdown_select.tsx
Adds search bar to dropdown component
https://github.com/user-attachments/assets/af1dfd24-81b9-4849-a3ab-b88164a3ccfa
Closes #1367
=> feat(frontend): add search bar to dropdown component

android/measure/src/main/java/sh/measure/android/storage/Database.kt
App exit table can get an update or insert query for the same session-pid when a session is continued. This PR makes the insertion safe by ignoring them. Otherwise this would silently cause an exception on the I/O thread. 
References #1333
=> fix(android): ignore duplicate inserts to app exit

frontend/dashboard/app/components/session_replay.tsx
Fixes incorrect time diff calculation on filtered events in session replay.
Fixes #1380
=> fix(frontend): calculate time diff b/w filtered events

android/measure/src/main/java/sh/measure/android/applaunch/AppLaunchCollector.kt, android/measure/src/main/java/sh/measure/android/applaunch/LaunchTracker.kt
Removes unnecessary logs with `level=error` added for launch tracking.
=> chore(android): remove unnecessary logs for launch tracking

android/measure-android-gradle/src/main/kotlin/sh/measure/asm/NavigationTransformer.kt
Updates `NavigationTransformer` to apply ASM transformation to latest `navigation-compose` library at the moment (8.3.0)
=> chore(android): support latest stable compose-navigation

android/measure/src/androidTest/java/sh/measure/android/FakeConfigProvider.kt, android/measure/src/androidTest/java/sh/measure/android/SessionTest.kt, android/measure/src/androidTest/java/sh/measure/android/SessionTestRobot.kt, android/measure/src/main/java/sh/measure/android/SessionManager.kt, android/measure/src/main/java/sh/measure/android/config/Config.kt, android/measure/src/main/java/sh/measure/android/config/ConfigProvider.kt, android/measure/src/main/java/sh/measure/android/config/InternalConfig.kt, android/measure/src/test/java/sh/measure/android/SessionManagerTest.kt, android/measure/src/test/java/sh/measure/android/fakes/FakeConfigProvider.kt
=> chore(android): add max session duration config

android/measure/src/main/java/sh/measure/android/RecentSession.kt, android/measure/src/main/java/sh/measure/android/SessionManager.kt, android/measure/src/test/java/sh/measure/android/SessionManagerTest.kt
We're using elapsed time since boot to store createdAt and lastEventTime for recent session. This allows us to ensure that session management does not get affected by any change in wall clock time.
However, we didn't handle the case where the device get rebooted and the atomic clock is reset. This PR fixes that.
closes #1393
=> fix(android): handle session management when elapsed time gets reset

android/measure/src/main/java/sh/measure/android/storage/PrefsStorage.kt
Use `sharedPrefs.commit` instead of `apply`. Commit will write to disk immediately to update the recent session state when app crashes. This gives a better chance for the write to succeed.
Closes #1440
=> fix(android): create new session if previous session crashed

android/measure/src/main/java/sh/measure/android/MeasureInitProvider.kt, android/measure/src/main/java/sh/measure/android/applaunch/AppLaunchCollector.kt, android/measure/src/main/java/sh/measure/android/applaunch/LaunchTracker.kt
The system APIs return uptime millis, using realtime elapsed will lead to wrong time calculation. This was changed as part of #1402. Reverting launch time to continue using uptime millis. 
Fixes #1437
=> fix(android): use uptime millis for cold launch instead of realtime elapsed

backend/api/filter/appfilter.go, backend/api/group/group.go, backend/api/measure/app.go, backend/api/measure/event.go, backend/api/numeric/numeric.go
Made pagination of Crash/ANR detail crashes duplication free. Improved overall performance and experience of Crash/ANR Overview and detail APIs.
- fixes #1418
=> fix(backend): improve crash/anr detail experience

self-host/clickhouse/20241031172411_alter_events_table.sql
Added new migration to create/drop data skipping indexes for Crash/ANR fingerprints. These indexes use bloom filter with a granularity value of 4.
- fixes #1454
=> chore(backend): add data skipping indexes for fingerprints

frontend/dashboard/app/components/exceptions_details.tsx
Crash detail page was not showing crash instance id because of a typo.
- fixes #1452
=> fix(frontend): crash detail not showing id

self-host/compose.prod.yml
To prevent disruption for self host-ers, apply a suitable compose restart policy for production environment.
- fixes #1457
=> chore(backend): apply suitable restart policy

backend/api/filter/appfilter.go, backend/api/filter/shortfilters.go, backend/api/main.go, backend/api/measure/app.go, backend/cleanup/cleanup/cleanup.go, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/utils/auth/auth.ts, self-host/postgres/20241102075104_create_short_filters_table.sql
Uses short codes for list filters
Closes #1408
=> feat(backend): use short codes for list filters

android/measure/src/main/java/sh/measure/android/config/Config.kt, android/measure/src/main/java/sh/measure/android/config/DefaultConfig.kt, android/measure/src/main/java/sh/measure/android/config/MeasureConfig.kt
* Update default session sampling rate to 0, meaning all events for non-crashed sessions will not be exported by default.
* Add `eventTypeExportAllowList` to include screen view, lifecycle activity and fragment events.
#1480
=> chore(android): collect all crashed session events and only launch & journey events for non-crashed sessions

ios/MeasureSDK/Exporter/BatchCreator.swift, ios/MeasureSDK/Exporter/PeriodicEventExporter.swift, ios/MeasureSDK/Gestures/GestureCollector.swift, ios/MeasureSDK/Gestures/GestureDetector.swift, ios/MeasureSDK/Lifecycle/LifecycleCollector.swift, ios/MeasureSDK/MeasureInitializer.swift, ios/MeasureSDK/RecentSession.swift, ios/MeasureSDK/SessionManager.swift, ios/MeasureSDK/Utils/Constants.swift, ios/MeasureSDK/Utils/TimeProvider.swift, ios/MeasureSDK/Utils/UserDefaultStorage.swift, ios/MeasureSDKTests/Exporter/BatchCreatorTests.swift, ios/MeasureSDKTests/Exporter/PeriodicEventExporterTests.swift, ios/MeasureSDKTests/Mocks/MockTimeProvider.swift, ios/MeasureSDKTests/SessionManagerTests.swift, ios/MeasureSDKTests/Utils/TimeProviderTests.swift, ios/TestApp/MockMeasureInitializer.swift
- update time creation logic to accommodate for clock skew
- create a new session if SDK version has been updated
Closes #1477
=> Ios session logic update & time provider refactor

frontend/dashboard/app/api/api_calls.ts
Handles empty attribute distributions
Before:
After:
Fixes #1475
=> fix(frontend): handle empty attr distributions

frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/dropdown_select.tsx
Move to limit/offset based pagination for Session Detail. Handle a couple of React duplicate key violations. Refactor and remove old old.
=> fix(frontend): better pagination in session detail

backend/api/measure/session.go
Fix an edge condition where `previous` would be set incorrectly to false when there are no results.
- fixes #1497
=> fix(backend): incorrect pagination when no data

backend/api/filter/appfilter.go
Add validation to handle if limit is requested as zero.
- fixes #1498
=> fix(backend): validate limit to not be zero

self-host/clickhouse/20241107074128_alter_sessions_table.sql, self-host/clickhouse/20241107074259_alter_sessions_table.sql
> [!NOTE]
> 
> **Maintainers**, please [run ClickHouse migrations](https://github.com/measure-sh/measure/tree/main/self-host/clickhouse#running-clickhouse-migrations).
Changed skip index type of `user_id` field in sessions table from `minmax` to `bloom_filter`.
- fixes #1504
=> chore(backend): change index type in sessions table

self-host/compose.yml
Changed the configuration of `restart` setting of `postgres` compose service to restart unless stopped explicitly. This enables self host-ers to perform maintenance tasks when necessary.
- fixes #1508
=> chore(backend): change postgres compose config

docs/hosting/README.md, docs/hosting/migration-guides/v0.4.x/README.md
Update self hosting and migration guide to add some missing info. Fixed a typo in migration guide.
=> docs(backend): fix typos and missing info

self-host/compose.yml
Modified compose configuration to use a more specific `clickhouse/clickhouser-server:24.10-alpine` image version. This fixes issues when running backfills using `clickhouse-client` as the older `clickhouse-client` does not support multiline queries.
Pinning to a more specific version ensures that docker compose will always attempt to pull this version before starting the containers.
=> fix(backend): use specific clickhouse image version

android/measure/src/androidTest/java/sh/measure/android/NoopPeriodicEventExporter.kt, android/measure/src/main/java/sh/measure/android/MeasureInternal.kt, android/measure/src/main/java/sh/measure/android/events/EventProcessor.kt, android/measure/src/main/java/sh/measure/android/exporter/Heartbeat.kt, android/measure/src/main/java/sh/measure/android/exporter/PeriodicEventExporter.kt, android/measure/src/main/java/sh/measure/android/networkchange/NetworkChangesCollector.kt, android/measure/src/test/java/sh/measure/android/exporter/PeriodicEventExporterTest.kt
Fixes and improves initialization logic:
* add reentrant lock to heartbeat to avoid any potential race conditions
* use reentrant lock for SDK start/stop
* disable power state, network changes collection in background
* standardize function names for register/unregister/pause/resume
* unregister AppLifecycleCollector correctly
#1532
=> fix(android): initialization issues

android/docs/internal-documentation.md, android/gradle/libs.versions.toml, android/measure/src/main/java/sh/measure/android/Measure.kt, android/measure/src/main/java/sh/measure/android/events/EventProcessor.kt, docs/android/README.md
Updates benchmarks and related documentation.
=> docs(android): update benchmarks & related information in README

android/measure/consumer-rules.pro, android/measure/src/main/java/sh/measure/android/MeasureInternal.kt, android/measure/src/main/java/sh/measure/android/exporter/Heartbeat.kt
Add keep rule for `AndroidComposeView` class name. Without this gesture detection breaks.
=> fix(android): add keep rule for AndroidComposeView

docs/api/dashboard/README.md
Update dashboard API documentation to document the PATCH `/apps/:id/rename` API.
- fixes #1544
=> docs(backend): document rename app api

frontend/dashboard/app/components/filters.tsx
Filters was sending a state update on selectedApp change as well as on the actual filter values changing.
This lead to creation of a short code with new app but old filter values causing bugs.
This commit only sends filter updates on filter value changes. Since values always get updated on selectedApp change, we will now get a single update on app + filter value changes.
Fixes #1557
=> fix(frontend): don't update filters on selectedApp change

backend/api/measure/app.go, backend/api/measure/event.go, backend/api/measure/session.go, backend/api/pairs/pairs.go
Handle versions & OS versions securely using database parameters when filtering.
- fixes #1562
=> fix(backend): filter versions and os versions securely

frontend/dashboard/app/components/session_replay_event_details.tsx
Fixes a bug by handling empty user_defined_attrs in session timeline
=> fix(frontend): handle empty user_defined_attrs in session timeline

frontend/dashboard/app/components/session_replay_event_cell.tsx
Truncates class names in session timeline event titles
Closes #1561
=> chore(frontend): truncate class names in session timeline event titles

frontend/dashboard/app/components/filters.tsx
root span names api was being called on non-span filter type. This commit fixes the if condition to prevent this.
Fixes #1568
=> fix(frontend): fix root span names api call

frontend/dashboard/__tests__/utils/time_utils.test.ts, frontend/dashboard/app/utils/time_utils.ts
Rounds milliseconds to nearest int
Fixes #1574
=> fix(frontend): round millis to nearest int

frontend/dashboard/app/components/dropdown_select.tsx
Makes whole checkbox container clickable in dropdown select component
Closes #1560
=> feat(frontend): make whole checkbox container clickable in dropdown select component

backend/api/event/attribute.go, backend/api/event/event.go, backend/api/measure/event.go, docs/api/sdk/README.md, self-host/clickhouse/20241210052709_alter_events_table.sql, self-host/sessionator/cmd/ingest.go, self-host/sessionator/cmd/record.go
Support ingesting iOS events in the PUT `/events` API.
- fixes #1586
- #1118
- #1139
=> feat(backend): support ios event ingestion

backend/api/event/attribute.go, backend/api/span/span.go
Validate all required event & span attributes before ingestion.
- fixes #1589
=> fix(backend): validate required event & span attributes

backend/api/main.go, backend/api/measure/app.go, docs/api/dashboard/README.md, frontend/dashboard/app/api/api_calls.ts
Spans with names like 'GET developer.android.com/...' cannot be passed as part of url path in Gin. It confuses the routing system and results in 404s.
This commit fixes the issue by passing in span names as query params instead of as part of the path.
Fixes #1575
=> fix(backend): make span name query param

backend/api/measure/event.go
Checkpoints were not formatted correctly during ingestion leading to failures. This PR formats them as required by clickhouse.
Fixes #1592
=> fix(backend): format checkpoints for ingestion

backend/api/filter/appfilter.go, backend/api/filter/shortfilters.go, backend/api/measure/app.go
When there are 2 apps with the exact same filter structure and values, the POST `/apps/:id/shortFilters` API mistakenly returns the matching short code which can be associated incorrectly with a different app. When this incorrect short code is then used in further APIs like GET `/apps/:id/metrics` and so on, they raise further errors.
This PR, includes the `appId` in the filter short code generation. This way, the generated code always remains unique for each app and hence can be safely used as the primary key of the `short_filters` table.
- fixes #1602
=> fix(backend): unexpected shortcodes gets created sometimes

frontend/dashboard/app/components/trace_viz.tsx
Span duration display on bar had several issues:
- text overflowing the span bar
- text color change in selected state not being visible in the overflowing part
- spans at end of trace not having enough space to render text
In this commit, we render the text above the bar.
Now, text color does not need to change in selected state and for spans near the end of the trace, text becomes horizontally scrollable.
Fixes #1595
=> fix(frontend): place span durations above bar

frontend/dashboard/app/components/trace_viz.tsx
Fix span sorting & null checkpoints handling
Fixes #1605
=> fix(frontend): fix span sorting & null checkpoints handling

backend/api/measure/event.go
Sessionator ingestion for iOS was failing because of a typo in the ingestion code.
- fixes #1621
=> fix(backend): sessionator ingestion failure

backend/api/measure/app.go, backend/api/timeline/cpu.go, backend/api/timeline/critical.go, backend/api/timeline/custom.go, backend/api/timeline/doc.go, backend/api/timeline/exit.go, backend/api/timeline/gesture.go, backend/api/timeline/launch.go, backend/api/timeline/lifecycle.go, backend/api/timeline/log.go, backend/api/timeline/massage.go, backend/api/timeline/memory.go, backend/api/timeline/nav.go, backend/api/timeline/network.go
This PR updates the session timeline API to support iOS events.
- fixes #1623
=> feat(backend): ios session timeline

frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/session_replay.tsx
This PR adds a memory usage plot for `memory_usage_abolute` events in session timeline detail page. Additionally, it fixes the legend to say 'KB' instead of 'MB'.
- fixes #1619
=> feat(frontend): add memory usage absolute plot in session timeline

android/measure/api/measure.api, android/measure/src/main/java/sh/measure/android/Measure.kt, android/measure/src/main/java/sh/measure/android/MeasureInternal.kt, docs/android/README.md
Exposes a new public API to get current session ID.
Fixes #1631
=> feat(android): expose API to get current session ID

.github/workflows/api.yml, backend/api/event/userdefattr.go, backend/api/event/userdefattr_test.go, docs/api/sdk/README.md
This PR fixes and improves support for number(both integers and floats) for user defined attributes.
- fixes #1620
=> fix(backend): handle large numbers in user defined attributes gracefully

self-host/sessionator/README.md, self-host/sessionator/cmd/help.go, self-host/sessionator/cmd/ingest.go, self-host/sessionator/cmd/metrics.go, self-host/sessionator/cmd/record.go, self-host/sessionator/cmd/remove.go, self-host/sessionator/cmd/rm.go, self-host/sessionator/cmd/root.go
This PR updates sessionator ingest command to clean all resources of an app. Also adds a new subcommand `remove apps` to entirely remove an app. Additionally, refactors all the commands to improve consistency.
- fixes #1464
- fixes #1629
=> chore(backend): remove all app resources in sessionator

self-host/compose.yml
On Docker Desktop for Mac, dashboard service would not auto-restart on compose restarts of its dependent service - `api`. This PR, removes the `depends_on` element from dashboard service thereby untethering the ordering of container creation of dashboard service from rest of the compose services.
For regular development, this change should not be a blocker - in fact, this leads to a faster developer feedback cycle, as developers do not need to wait for restart of the dashboard service. But on production if the `dashboard` service is started before `api` service, for a brief moment network requests to `api` service will fail while the service is coming up.
If users report this to be an issue, we can override the behavior on production using compose overrides, but for now, we'll continue …
=> fix(backend): dashboard no longer depends on api service

self-host/sessionator/cmd/remove.go, self-host/sessionator/cmd/rm.go
This PR fixes a nil pointer deference issue happening when removing apps using `sessionator remove apps` command.
=> fix(backend): nil pointer dereference in remove apps

backend/cleanup/cleanup/cleanup.go
This PR, updates cleanup service to remove expired event filters, event metrics, span filters, span metrics, sessions and user defined attributes.
- fixes #1530
=> chore(backend): cleanup expired resources

android/docs/internal-documentation.md, android/measure/src/androidTest/java/sh/measure/android/FakeConfigProvider.kt, android/measure/src/androidTest/java/sh/measure/android/TestMeasureInitializer.kt, android/measure/src/main/java/sh/measure/android/MeasureInitializer.kt, android/measure/src/main/java/sh/measure/android/MeasureInternal.kt, android/measure/src/main/java/sh/measure/android/config/Config.kt, android/measure/src/main/java/sh/measure/android/config/ConfigProvider.kt, android/measure/src/main/java/sh/measure/android/config/InternalConfig.kt, android/measure/src/main/java/sh/measure/android/storage/Database.kt, android/measure/src/main/java/sh/measure/android/storage/PeriodicSignalStoreScheduler.kt, android/measure/src/main/java/sh/measure/android/storage/SignalStore.kt, android/measure/src/test/java/sh/measure/android/fakes/FakeConfigProvider.kt, android/measure/src/test/java/sh/measure/android/fakes/FakeSignalStore.kt, android/measure/src/test/java/sh/measure/android/storage/DatabaseTest.kt, android/measure/src/test/java/sh/measure/android/storage/SignalStoreTest.kt, android/sample/build.gradle.kts
* Buffer events and spans in `SignalStore`
* Persist buffer at time of crash, when app goes to background and periodically every 3 seconds.
Closes: https://github.com/measure-sh/measure/issues/1642
=> refactor(android): implement batch insertions of events and spans in db

android/measure/src/main/java/sh/measure/android/layoutinspector/LayoutSnapshot.kt
Removes an unnecessary log which would construct a long string and attempt to log if even if logging is disabled.
=> Remove uneeded log

android/measure/src/main/java/sh/measure/android/NoopThermalStateManager.kt, android/measure/src/main/java/sh/measure/android/PowerStateProvider.kt, android/measure/src/main/java/sh/measure/android/ThermalStateManager.kt, android/measure/src/main/java/sh/measure/android/ThermalStateManagerImpl.kt
PowerManager.OnThermalStatusChangedListener is available only for API 29 and above. This PR makes sure that this class is only accessed for APIs when it's available.
Closes #1660
=> refactor(android): avoid accessing thermal status change for older APIs

backend/api/measure/session.go
This PR addresses an issue where duplicate sessions would be queried with inaccurate session duration computations. Query performance overhead for large sessions is negligible.
- fixes #1556
=> fix(backend): duplicate sessions shown in sessions overview

android/measure/src/main/java/sh/measure/android/attributes/AttributeValue.kt, android/measure/src/test/java/sh/measure/android/storage/EventExtensionsKtTest.kt
Updates serialization of user defined attributes to always serialize numbers as _numbers_ instead of strings.
References #1620
=> fix(android): serialize numbers as numbers instead of string in user def attrs

android/measure/api/measure.api, android/measure/src/main/java/sh/measure/android/Measure.kt, android/measure/src/main/java/sh/measure/android/MeasureInternal.kt, android/measure/src/main/java/sh/measure/android/events/EventType.kt, android/measure/src/main/java/sh/measure/android/events/UserTriggeredEventCollector.kt, android/measure/src/main/java/sh/measure/android/storage/EventExtensions.kt, android/measure/src/test/java/sh/measure/android/events/SignalProcessorTest.kt, android/measure/src/test/java/sh/measure/android/events/UserTriggeredEventCollectorImplTest.kt, android/measure/src/test/java/sh/measure/android/fakes/TestData.kt, android/measure/src/test/java/sh/measure/android/storage/EventExtensionsKtTest.kt, docs/android/README.md, docs/api/sdk/README.md
Removes the deprecated navigation event from Android SDK and updates docs.
closes #1600
=> feat(android): remove deprecated navigation event

docs/android/README.md
Adds a section for minimum self-host version required for a given SDK version.
Closes #1664
=> docs(android): add minimum version compatibility

frontend/dashboard/__tests__/utils/number_utils.test.ts, frontend/dashboard/app/components/session_replay.tsx, frontend/dashboard/app/utils/number_utils.ts
This PR converts kilobytes to megabytes before showing in memory usage plot in session timeline. Both `memory_usage` and `memory_usage_absolute` events are handled.
- fixes #1633
=> fix(frontend): show memory usage in mbs in session timeline

android/measure/src/main/java/sh/measure/android/layoutinspector/LayoutInspector.kt
Since #1551 the target id in gesture click events incorrectly contained a hardcoded "id:" prefix. This has been removed.
=> fix(android): remove unneeded view id prefix in gesture events

frontend/dashboard/app/components/session_replay_event_details.tsx
Http event display in session timeline had two issues:
- start_time & end_time keys are ms in uptimes but were being parsed inccoreclty as timestamps
- request & response headers were not being shown
This commit:
- ignores start_time & end_time for http events
- formats and displays request & response headers
Fixes #1663
=> fix(frontend): handle incorrect http event display in session timeline

ios/MeasureSDK/Measure.swift
Exposes a public API to get current session ID.
Closes #1635
=> feat(ios): expose API to get current session ID

.commitlintrc.js
This PR extends commitlint's config to support additional scopes.
- fixes #1702
=> chore(backend): add new scopes to commitlint

cliff.toml
This PR adds support for `flutter` & `react-native` to git cliff for generating appropriate changelogs during releases.
- fixes #1704
=> chore(backend): support `flutter` & `rn` in cliff config

cliff.toml
This PR improves the overall formatting of automated change logs.
- fixes #1293
=> chore: improve automated changelog formatting

backend/api/measure/auth.go
Replaces email with new user login log
Closes #1718
=> chore(backend): replace email with new user login log

ios/DemoApp/AppDelegate.swift, ios/DemoApp/Controller/ObjcDetailViewController.m, ios/DemoApp/Controller/ViewController.swift, ios/MeasureSDK.xcodeproj/project.pbxproj, ios/MeasureSDK/Config/Config.swift, ios/MeasureSDK/CoreData/Entities/EventEntity.swift, ios/MeasureSDK/CoreData/EventStore.swift, ios/MeasureSDK/Events/EventType.swift, ios/MeasureSDK/Events/ScreenViewData.swift, ios/MeasureSDK/Events/UserTriggeredEventCollector.swift, ios/MeasureSDK/Exporter/EventSerializer.swift, ios/MeasureSDK/Measure.swift, ios/MeasureSDK/MeasureInitializer.swift, ios/MeasureSDK/MeasureInternal.swift, ios/MeasureSDK/XCDataModel/MeasureModel.xcdatamodeld/MeasureModel.xcdatamodel/contents
Provides public APIs to track screen view events.
Measure tracks UIViewControllers by default, but in cases where a custom navigation is used, devs can use this api to track screen views.
```swift
Measure.shared.trackScreenView("Home")
```
```objc
[[Measure shared] trackScreenView:@"Home"]
```
Closes #1580
=> chore(ios): add screen view event

docs/hosting/README.md
This PR improves formatting of the self hosting guide's FAQ section.
=> docs(backend): improve self hosting faq section

backend/api/filter/appfilter.go
This PR removes the datetime from the filters read query for user defined attributes.
- fixes #1737
=> fix(backend): query all user defined attributes

frontend/dashboard/app/[teamId]/apps/page.tsx, frontend/dashboard/app/[teamId]/overview/page.tsx, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/[teamId]/traces/page.tsx, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/dropdown_select.tsx, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/components/exceptions_overview.tsx, frontend/dashboard/app/components/filters.tsx, frontend/dashboard/app/components/user_def_attr_selector.tsx, self-host/clickhouse/schema.sql, self-host/postgres/schema.sql
Implements user defined attribute filters
Closes #1531
=> feat(frontend): implement ud attr filters

self-host/sessionator/README.md, self-host/sessionator/app/scan.go, self-host/sessionator/cmd/ingest.go
This PR adds a new `--skip-apps` option to sessionator's ingest command allowing us to skip certain apps from ingestion.
- fixes #1743
=> chore(backend): add `--skip-apps` option

backend/api/event/event.go, backend/api/event/frame.go, backend/api/journey/android.go, backend/api/journey/ios.go, backend/api/measure/app.go, backend/api/measure/event.go, backend/api/numeric/numeric.go, backend/api/platform/platform.go, self-host/sessionator/README.md
This PR adds support for **validating**, **grouping**, **fingerprinting**, **ingesting**, **storing** and **retrieving** iOS exceptions throughout the system surface. Android exceptions and ANRs should continue to work without regression.
> [!NOTE]
> _Builds, mappings and symbolication would be implemented in a different PR._
- fixes #1724
=> feat(backend): add support for iOS exceptions

ios/DemoApp/AppDelegate.swift, ios/MeasureSDK.xcodeproj/project.pbxproj, ios/MeasureSDK/Config/BaseConfigProvider.swift, ios/MeasureSDK/Config/Config.swift, ios/MeasureSDK/Config/DefaultConfig.swift, ios/MeasureSDK/Config/InternalConfig.swift, ios/MeasureSDK/Config/MeasureConfig.swift, ios/MeasureSDK/CoreData/DataCleanupService.swift, ios/MeasureSDK/CoreData/Entities/EventEntity.swift, ios/MeasureSDK/CoreData/EventStore.swift, ios/MeasureSDK/CoreData/SessionStore.swift, ios/MeasureSDK/Events/EventProcessor.swift, ios/MeasureSDK/Exporter/EventSerializer.swift, ios/MeasureSDK/MeasureInitializer.swift, ios/MeasureSDK/MeasureInternal.swift, ios/MeasureSDK/SessionManager.swift, ios/MeasureSDK/XCDataModel/MeasureModel.xcdatamodeld/MeasureModel.xcdatamodel/contents, ios/MeasureSDKTests/Config/BaseConfigProviderTests.swift, ios/MeasureSDKTests/CoreData/DataCleanupServiceTests.swift, ios/MeasureSDKTests/CoreData/SessionStoreTests.swift, ios/MeasureSDKTests/Event/CustomEventCollectorTests.swift, ios/MeasureSDKTests/Event/EventProcessorTests.swift, ios/MeasureSDKTests/Exporter/EventSerializerTests.swift, ios/MeasureSDKTests/Helper/TestDataGenerator.swift, ios/MeasureSDKTests/Mocks/MockConfigProvider.swift, ios/MeasureSDKTests/Mocks/MockEventStore.swift, ios/MeasureSDKTests/Mocks/MockSessionManager.swift, ios/MeasureSDKTests/SessionManagerTests.swift, ios/TestApp/AppDelegate.swift, ios/TestApp/MockMeasureInitializer.swift
This PR contains the below
- Session sampling rate logic updated
- Data clean up service added
- Tests
Closes #1395
=> chore(ios): add session sampling and data cleanup

frontend/dashboard/app/components/dropdown_select.tsx
Allows unchecking last item in dropdown select if "None" is available
Closes #1758
=> chore(frontend): allow unchecking last item in dropdown select if "None" is available

backend/api/span/span.go
Only apply span statuses where clause if available in span apis
Fixes #1759
=> fix(backend): only apply span statuses where clause if available

frontend/dashboard/app/components/filters.tsx
Hides filter pill when no span statuses are selected
Fixes #1763
=> fix(frontend): hide filter pill when no span statuses are selected

backend/api/event/event.go, docs/api/sdk/README.md
This PR adds a new `terminated` type for `lifecycle_app.type` for iOS platforms.
- fixes #1754
=> chore(backend): add lifecycle app type for ios

backend/api/measure/event.go
This PR cleans up event batches that are stuck in a pending state for a long time. This prevents certain situations where ingestion can get into a `429 Too Many Requests` loop and hence stall ingestion.
> [!NOTE]
>
> Only stale event batches having the same id as the previous batch gets removed. So, other event batches are not affected from this change.
The updated duplicate event batch check flow is as follows.
```mermaid
flowchart TB
id1(Start) --> id2(Fetch request with `msr-req-id`)
id2 --> id3{Is status pending?}
id3 --y--> id4{Has `created_at` passed timeout threshold?}
id3 --n--> id5(Return `202 Accepted` known event request)
id5 --> stop(Stop)
id4 --y--> del(Delete pending event request)
id4 --n--> tooMany(Return `429 Too Many Requests` response)
tooMany --> stop
del --> …
```
=> fix(backend): clean up event batches stuck for a long time

android/gradle/libs.versions.toml, android/measure-android-gradle/build.gradle.kts
This PR changes the Measure gradle plugin default Java version to 11. This should allow apps still on Java 11 to be able to use Measure. Functional test continue to run for Java 17 and all supported AGP versions.
fixes: #1729
=> fix(android): support java 11

backend/api/measure/event.go
This PR fixes an issue where for some cases attachments like SVG layout snapshots would not render because of unexpected mime types (`application/octet-stream`) inference. Attachment mime types would now be inferred from a more reliable source of information i.e. from the event batch itself rather than reading from the multipart request's form field headers.
- fixes #1736
=> fix(backend): svg layout attachments are not visible sometimes

frontend/dashboard/app/components/user_def_attr_selector.tsx
Makes user def attr dropdown stay in viewport
Fixes #1783
=> fix(frontend): make user def attr dropdown stay in viewport

android/gradle/libs.versions.toml, android/measure/build.gradle.kts, android/measure/src/androidTest/AndroidManifest.xml, android/measure/src/androidTest/java/sh/measure/android/EventsTest.kt, android/measure/src/androidTest/java/sh/measure/android/EventsTestRobot.kt, android/measure/src/test/java/sh/measure/android/networkchange/InitialNetworkStateProviderTest.kt, android/measure/src/test/java/sh/measure/android/networkchange/NetworkChangesCollectorTest.kt, android/measure/src/test/java/sh/measure/android/utils/ScreenshotCollectorTest.kt
* Removed or ignored tests which used @Config(sdk = []) as this is causing
the tests to go OOM.
* add testOptions.targetSdk to resolve tests from using old SDK versions
* update android test manifest file with required permissions so that the test process
does not crash
Please add a summary of the changes
References #(issue) #1819
=> chore(android): update robolectric

frontend/dashboard/app/[teamId]/sessions/[appId]/[sessionId]/page.tsx
Adds build number to session replay attr display
Closes #1829
=> feat(frontend): add build number to session replay attr display

frontend/dashboard/app/[teamId]/bug_reports/[appId]/[bugReportId]/page.tsx
show user def attrs in bug report details
Closes #1825
=> feat(frontend): show user def attrs in bug report details

backend/api/measure/app.go, backend/api/timeline/bugreport.go, frontend/dashboard/app/components/session_replay_event_cell.tsx, frontend/dashboard/app/components/session_replay_event_details.tsx
Shows bug reports in session timeline
Closes #1827
=> feat(frontend): show bug reports in session timeline

ios/README.md, ios/Scripts/upload_dsym_build_phases.sh, ios/Scripts/upload_dsyms.sh
This pr contains
- Scripts to upload dsyms to server.
- Updated Docs.
Closes #1639
=> chore(ios): add scripts to upload dsyms

.github/workflows/flutter.yml
Unit tests for iOS are failing on CI due to code signing issues. Disabling tests temporarily.
References #1847
=> ci(flutter): disable ios tests for flutter

frontend/dashboard/app/[teamId]/sessions/[appId]/[sessionId]/page.tsx, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/session_timeline.tsx, frontend/dashboard/app/components/session_timeline_event_cell.tsx, frontend/dashboard/app/components/session_timeline_event_details.tsx, frontend/dashboard/app/components/session_timeline_seekbar.tsx
Renames session 'replay' to 'timeline'
Closes #1835
=> chore(frontend): rename session 'replay' to 'timeline'

backend/cleanup/cleanup/cleanup.go
Refactor event, attachment & span cleanup to match with cleanup code of other resources.
Closes #1840
=> chore(backend): refactor event, attachment & span cleanup

backend/api/go.mod, backend/cleanup/go.mod, backend/migrator/go.mod, go.work
The go toolchain version is not in the updated format. It should be go 1.N.P while they were in 1.N format. This will ensure go tools in CI and local environments pick the correct tooling versions.
=> chore(backend): update go toolchain version

self-host/sessionator/app/build.go, self-host/sessionator/cmd/record.go
Fix a CodeQL alert in `sessionator record` command. The error occurred in the code path of creating build size toml object while reading and writing `build.toml` files.
[See the alert](https://github.com/measure-sh/measure/security/code-scanning/35)
=> fix(backend): codeql integer conversion error

frontend/dashboard/app/components/session_timeline.tsx
Handles session timeline with no events
Fixes #1887
=> fix(frontend): handle session timeline with no events

self-host/sessionator/cmd/remove.go, self-host/sessionator/cmd/rm.go
Update sessionator `--clean/--clean-all` to remove all app resources including bug reports and span user defined attributes.
- fixes #1895
=> chore(backend): clean more resources in sessionator

backend/api/codec/codec.go, backend/api/measure/event.go, self-host/sessionator/app/scan.go, self-host/sessionator/cmd/ingest.go
This PR fixes some of the issues discovered in sessionator record and ingest operations during our recent testing.
=> fix(backend): sessionator record & ingest errors

backend/api/event/event.go, docs/api/sdk/README.md, self-host/clickhouse/20250315090713_alter_events_table.sql
> [!NOTE]
>
> ## To Maintainers
>
> Please run ClickHouse migrations by [following this guide.](https://github.com/measure-sh/measure/blob/main/self-host/clickhouse/README.md)
This PR modifies the column width of `cpu_usage.clock_speed` in ClickHouse events table and in server code from `uint32` to `uint64`. iOS necessitates this otherwise `cpu_usage.clock_speed` could become 0 which is not acceptable by the event ingestion pipeline.
- fixes #1903
=> fix(backend): fix an issue where clock_speed validation was failing

backend/api/measure/app.go, backend/api/timeline/gesture.go, frontend/dashboard/app/components/session_timeline_event_details.tsx
In Session Timeline view, we only render attachments for `gesture_click` gesture events. This behavior works as expected with respect to Android platform, but for iOS platform, we capture attachments like layout snapshots for `gesture_long_click` and `gesture_scroll` events along with `gesture_click` events.
This PR modifies the GET `/apps/:id/sessions/:sessionId` API to return attachment data for `gesture_scroll` and `gesture_long_click` events when available.
Additionally, the Session Timeline details page has been modified to render these attachments.
- fixes #1909
=> Render attachments for `gesture_scroll` & `gesture_long_click` events in session timeline

backend/api/measure/mapping.go, backend/api/symbol/dif.go, backend/api/symbol/dif_test.go
This PR modfies the PUT `/builds` API to accept `.dylib` binary files for iOS along with regular non-dylib binaries. This change ensures that users who are producing debug builds in newer Xcode versions also enjoy iOS symbolication.
- fixes #1913
=> chore(backend): support .dylib mapping files in ios

frontend/dashboard/app/components/exceptions_overview.tsx
This PR improves the formatting of displaying crashes on the crash overview page.
- fixes #1915
=> fix(frontend): improve crash display for ios

docs/api/sdk/README.md
This PR updates the SDK API documentation with updated information for PUT `/builds` API.
- fixes #1917
=> docs(backend): update sdk api docs

self-host/sessionator/cmd/rm.go
This PR fixes ingest `--clean-all` flag to work as expected. An optional parameter was missed when creating an S3 client for operating on attachments bucket.
- fixes #1923
=> fix(backend): fix issue with sessionator clean-all flag

android/gradle/libs.versions.toml, android/gradle/wrapper/gradle-wrapper.properties, android/measure-android-gradle/src/functionalTest/kotlin/sh/measure/MeasurePluginTest.kt
Version changes:
AGP -> 8.9.0
androidx.core -> 1.13.1 to remain compatible with apps on Android 34
Fixes #1921
=> chore(android): upgrade AGP and downgrade androidx.core

backend/api/symbolicator/symbolicator.go
This PR fixes a panic that was happening with ANR symbolication.
- fixes #1919
=> fix(backend): fix a panic during anr symbolication

backend/api/symbolicator/payload.go, backend/api/symbolicator/symbolicator.go, self-host/compose.yml
This PR works around a bug in Sentry's Symbolicator JVM symbolication response where it would produce unexpected symbolication outcomes for certain stacktraces containing lambda functions.
- fixes #1920
=> fix(backend): fix partial android symbolication

backend/api/measure/mapping.go, backend/api/server/server.go, docs/api/sdk/README.md
This PR removes mapping file maximum size validation in PUT `/builds` API.
- fixes #1930
=> fix(backend): remove mapping file size validation

docs/hosting/README.md, self-host/config.sh, self-host/install.sh
This PR updates the `self-host/install.sh` script to accommodate recent symbolicator service migration, environment variable migration and other such similar updates.
- fixes #1886
=> chore(backend): update migration script

ios/Sources/MeasureSDK/Swift/CoreData/CoreDataManager.swift, ios/Sources/MeasureSDK/Swift/CrashReporter/SystemCrashReporter.swift, ios/Sources/MeasureSDK/Swift/MeasureInitializer.swift, ios/TestApp/MockMeasureInitializer.swift
When `PLCrashReporter` is initalized in its default configuration, it handles unhandled exception and then manually aborts the application. This results in PLCrashReporter.m showing up in stacktraces instead of the original crash stacktrace.
Setting `shouldRegisterUncaughtExceptionHandler` to `false` lets us skip this behaviour and unhandled exceptions crash in their respective classes.
Closes #1934
=> chore(ios): update plcrashreporter config

backend/api/measure/event.go, backend/api/span/span.go, backend/api/symbolicator/symbolicator.go
This PR symbolicates span name classes that look like.
- Activity TTID {class_name}
- Fragment TTID {class_name}
- fixes #1905
=> feat(backend): symbolicate ttid span classes

backend/api/measure/session.go
This PR fixes an issue where paginating GET `/apps/:id/sessions` API would fail when combined with any user defined attributes.
- fixes #1946
=> fix(backend): broken session pagination with user defined attrs

android/measure/src/main/java/sh/measure/android/applaunch/LaunchTracker.kt, android/measure/src/main/java/sh/measure/android/lifecycle/FragmentLifecycleCollector.kt, android/measure/src/main/java/sh/measure/android/tracing/SpanConstants.kt, android/measure/src/test/java/sh/measure/android/tracing/SpanNameTest.kt
Truncate the TTID span names to always fit within the max span name length.
Fixes #1951
=> fix(android): truncate TTID span names to fit max span length

self-host/install.sh
This PR modifies `self-host/install.sh` to use `docker-compose` binary if available in the runtime environment. If it's not available, then fall back to using the regular `docker compose` for all compose command invocations.
- fixes #1961
=> chore(backend): change compose command detection logic

backend/api/filter/appfilter.go, backend/api/measure/app.go, backend/api/measure/bugreport.go, backend/api/measure/event.go, backend/api/measure/session.go, backend/api/span/span.go, self-host/clickhouse/20250325045646_replace_user_def_attrs_table.sql, self-host/clickhouse/20250325052401_alter_user_def_attrs_mv.sql, self-host/clickhouse/20250325094723_replace_span_user_def_attrs_table.sql, self-host/clickhouse/20250325100452_alter_span_user_def_attrs_mv.sql
> [!NOTE]
>
> ## To Maintainers
>
> Please run ClickHouse migrations. [Follow this guide](https://github.com/measure-sh/measure/blob/main/self-host/clickhouse/README.md#running-clickhouse-migrations)
This PR modifies `user_def_attrs`, `span_user_def_attrs` table and `user_def_attrs_mv`, `span_user_def_attrs_mv` materialized view to add a `ver` table parameter for ReplacingMergeTree engine. Additionally, each call site(s) of user defined attributes gain the `final` clause.
- fixes #1939
=> fix(backend): filter duplicate ud attribute keys

docs/ios/README.md, docs/ios/features/feature_navigation_and_lifecycle.md, ios/DemoApp/Controller/ObjcDetailViewController.h, ios/DemoApp/Controller/ViewController.swift, ios/MeasureSDK.xcodeproj/project.pbxproj, ios/PublicApi/Measure.swiftinterface, ios/PublicApi/MeasureSDK.swiftinterface, ios/Sources/MeasureSDK/Objc/include/MSRViewController.h, ios/Sources/MeasureSDK/Swift/Http/MSRNetworkInterceptor.swift, ios/Sources/MeasureSDK/Swift/Http/URLSessionTaskInterceptor.swift, ios/Sources/MeasureSDK/Swift/Lifecycle/MsrViewController.swift, ios/Sources/MeasureSDK/Swift/Measure.swift, ios/TestApp/ViewController.swift
Updated the below things in iOS docs.
- Updated table of content and restructured the ios README.
- Rename `MsrNetworkInterceptor` to `MSRNetworkInterceptor`.
- Links for upload dsym scripts added.
- Rename `MeasureViewController` to `MsrViewController`.
- Clarification on the usages of `MsrViewController` and `MSRViewController` marked as bold.
Closes #1954
=> docs(ios): update readme

ios/Sources/MeasureSDK/Swift/Config/ClientInfo.swift, ios/Sources/MeasureSDK/Swift/Measure.swift, ios/Sources/MeasureSDK/Swift/Utils/Constants.swift
Fixes the below issues:
- When the apiKey is sent, the SDK gets initialized but logs message `Measure apiKey is missing, skipping initialization`. Removed the incorrect log messages.
- SDK gets initialized even when apiUrl is nil.
Fixes #1968
=> Ios api key url check

backend/api/measure/bugreport.go, backend/api/measure/event.go, backend/api/measure/session.go, backend/api/span/span.go
This PR fixes issues related to duplication on sessions overview page as well as matching of user defined attributes on sessions, spans and bug reports overview pages.
- fixes #1949
- fixes #1950
=> fix(backend): mismatch and duplicate sessions

docs/hosting/README.md, docs/hosting/migration-guides/README.md, docs/hosting/migration-guides/v0.6.x/README.md, self-host/migrations/v0.6.x-data-backfills.sh
This PR adds a data backfilling script to populate `user_def_attrs` table as a migration step. Also, added a migration guide for upgrading to `v0.6.x`.
- fixes #1976
=> chore(backend): add data backfill for upcoming release

docs/ios/README.md, docs/ios/configuration-options.md, ios/MeasureSDK.xcodeproj/project.pbxproj, ios/PublicApi/Measure.swiftinterface, ios/Sources/MeasureSDK/Swift/Config/BaseConfigProvider.swift, ios/Sources/MeasureSDK/Swift/Config/Config.swift, ios/Sources/MeasureSDK/Swift/Config/DefaultConfig.swift, ios/Sources/MeasureSDK/Swift/Config/MeasureConfig.swift, ios/Sources/MeasureSDK/Swift/Http/HttpEventCollector.swift, ios/Sources/MeasureSDK/Swift/Http/HttpEventValidator.swift, ios/Sources/MeasureSDK/Swift/Http/MSRNetworkInterceptor.swift, ios/Sources/MeasureSDK/Swift/Http/NetworkInterceptorProtocol.swift, ios/Sources/MeasureSDK/Swift/Http/URLSessionTaskInterceptor.swift, ios/Sources/MeasureSDK/Swift/MeasureInitializer.swift, ios/TestApp/MockMeasureInitializer.swift, ios/Tests/MeasureSDKTests/Http/HttpEventValidatorTests.swift, ios/Tests/MeasureSDKTests/Mocks/MockConfigProvider.swift
Added the below properties to measure config
- trackHttpHeaders
- trackHttpBody
- httpHeadersBlocklist
- httpUrlBlocklist
- httpUrlAllowlist
This PR also contains:
- Tests
- Moved common logic from `NetworkInterceptorProtocol` and `URLSessionTaskInterceptor` to `HttpEventValidator` which check if a Http event needs to be tracked based on `httpHeadersBlocklist`, `httpUrlBlocklist` and `httpUrlAllowlist`
Closes #1979
=> chore(ios): add http event configurations to measure config

backend/api/measure/mapping.go
This PR fixes a bug where older Android SDKs using android-gradle-plugin@0.7.0 or older would fail uploading build info and build mapping because of a validation check where the server tries to determine the app's platform before proceeding with the processing and uploading of builds.
For the fix, the server tries to determine the app's platform, if it can't, it tries to set platform from the request payload, if it can't it assumes and sets the platform to Android if the `mapping_type` in the request payload is set to `proguard`.
```mermaid
flowchart
Start([Start]) --> DecisionA{App's platform is set?}
DecisionA --> |No| DecisionB{Request has \`platform\`?}
DecisionB --> |No| DecisionC{Is \`mapping_type\`=\`proguard\`?}
DecisionC --> |No| Fail
DecisionA --> |Yes| Proceed
DecisionC --> …
```
=> fix(backend): broken builds api for older android sdks

android/measure-android-gradle/src/main/kotlin/sh/measure/BuildUploadTask.kt, android/measure-android-gradle/src/test/kotlin/sh/measure/BuildUploadTaskTest.kt
Adds `platform` as `android` to `/builds` API request.
Closes #1985
=> chore(android): add platform to builds API request

ios/Tests/MeasureSDKTests/Exporter/HeartbeatTests.swift
The iOS tests are flaky because of the random failure of HeartBeatTests. 
Because the tests run in a multithreaded environment, the `pulse` function needs to be thread-safe. This is what was causing the inconsistancy.
Closes #1942
=> chore(ios): update heartbeat tests

.github/workflows/ios.yml
Remove swift lint check from ci. This will be added later as a pre-commit hook.
References #2011
=> chore(ios): remove swift-lint check on ci

docs/android/README.md
Improve the documentation to reflect behavior of SDK when in "stopped" state.
Closes #2012
=> docs(android): behaviour of SDK when stopped

android/measure/src/test/java/sh/measure/android/events/UserTriggeredEventCollectorImplTest.kt, android/measure/src/test/java/sh/measure/android/exceptions/UnhandledExceptionCollectorTest.kt
Comparing the exception object makes tests flaky as the thread state can be different at the time when the exception object is created vs when the `ExceptionData` object is created. This PR changes the assertion to not do a deep equals check on the exceptions object.
Fixes #1991
=> test(android): fix flaky exception tests

android/measure-android-gradle/src/main/kotlin/sh/measure/ExtractManifestDataTask.kt, android/measure-android-gradle/src/main/kotlin/sh/measure/MeasurePlugin.kt, android/measure-android-gradle/src/test/kotlin/sh/measure/ExtractManifestDataTaskTest.kt
Adds a validation to ensure API_KEY starts with expected `msrsh` prefix.
Fixes #2023
=> chore(gradle): add validation for API_KEY

frontend/dashboard/app/[teamId]/layout.tsx
Handles nav link clicks on same page. When left nav is clicked while on the same page as the nav link:
- Nav link remains clickable
- Query params should are preserved
- Page is not reloaded
Closes #2032
=> feat(frontend): handle nav link clicks on same page

ios/DemoApp/AppDelegate.swift, ios/Sources/MeasureSDK/Swift/MeasureInternal.swift, ios/Tests/MeasureSDKTests/CoreData/SessionStoreTests.swift, ios/Tests/MeasureSDKTests/SessionManagerTests.swift
This PR contains below changes.
- Fixed iOS sdk not auto-starting when autostart is set to true. 
- Fix failing tests.
Fixes #2035
=> fix(ios): start the sdk when autostart is enabled

flutter/measure_flutter/android/build.gradle
Flutter checks are failing due to older SDK version specified in Flutter Android Plugin. All Flutter workflows are currently failing: https://github.com/measure-sh/measure/pull/2042
This PR fixes the issue.
=> ci(flutter): update android sdk version

docs/api/sdk/README.md
Remove duplicate sections for `frame` and `binary_image` from sdk api docs.
Closes #2037
=> docs: update sdk api readme

android/measure/src/androidTest/java/sh/measure/android/EventsTest.kt, android/measure/src/androidTest/java/sh/measure/android/FakeConfigProvider.kt, android/measure/src/main/java/sh/measure/android/Measure.kt, android/measure/src/main/java/sh/measure/android/config/Config.kt, android/measure/src/main/java/sh/measure/android/config/ConfigProvider.kt, android/measure/src/main/java/sh/measure/android/config/InternalConfig.kt, android/measure/src/main/java/sh/measure/android/events/DefaultEventTransformer.kt, android/measure/src/main/java/sh/measure/android/events/Event.kt, android/measure/src/main/java/sh/measure/android/events/EventType.kt, android/measure/src/main/java/sh/measure/android/events/SignalProcessor.kt, android/measure/src/main/java/sh/measure/android/exporter/MultipartDataFactory.kt, android/measure/src/main/java/sh/measure/android/exporter/NetworkPackets.kt, android/measure/src/main/java/sh/measure/android/storage/Database.kt, android/measure/src/main/java/sh/measure/android/storage/DbConstants.kt, android/measure/src/main/java/sh/measure/android/storage/Entities.kt, android/measure/src/main/java/sh/measure/android/storage/EventExtensions.kt, android/measure/src/test/java/sh/measure/android/anr/AnrCollectorTest.kt, android/measure/src/test/java/sh/measure/android/exporter/ExporterTest.kt, android/measure/src/test/java/sh/measure/android/exporter/MultipartDataFactoryTest.kt, android/measure/src/test/java/sh/measure/android/fakes/FakeConfigProvider.kt, android/measure/src/test/java/sh/measure/android/fakes/TestData.kt, android/measure/src/test/java/sh/measure/android/okhttp/OkHttpEventCollectorTest.kt, android/measure/src/test/java/sh/measure/android/storage/DatabaseTest.kt, android/measure/src/test/java/sh/measure/android/storage/EventEntityTest.kt, android/measure/src/test/java/sh/measure/android/storage/EventExtensionsKtTest.kt
Converts event type from strings to enum:
- This is in general better for type safety
- Event type will be made public for flutter integration exposing it as an enum makes it a better API and allows validations to be simpler.
=> chore(android): convert event type to enum

docs/hosting/README.md, self-host/compose.prod.yml, self-host/compose.yml, self-host/install.sh
This PR adds support for `--podman` flag in `self-host/install.sh` script to setup and use podman as an alternative to docker.
- fixes #2051
=> fix(backend): add podman support

frontend/dashboard/app/[teamId]/bug_reports/page.tsx, frontend/dashboard/app/[teamId]/overview/page.tsx, frontend/dashboard/app/[teamId]/sessions/page.tsx, frontend/dashboard/app/[teamId]/traces/page.tsx, frontend/dashboard/app/components/exceptions_details.tsx, frontend/dashboard/app/components/exceptions_overview.tsx, frontend/dashboard/app/components/filters.tsx
When filters api call returns a no data or not onboarded state, we were not clearing previously set filters and also not updating filters in the pages (due to changes being ignored because of ready flag being false).
This PR clears filters on API failure status and applies filter changes appropriately.
Fixes #2056
=> fix(frontend): filters not updating on no data/not onboarded states

backend/api/measure/user.go
Gets own team correctly when user is owner of mutiple teams
Fixes #2068
=> fix(backend): get own team correctly when user is owner of multiple teams

ios/Sources/MeasureSDK/Swift/Utils/SysCtl.swift
Updated the logic to generate cpu frequency.
Earlier, we relied on getting the CPU frequency from chip name, now we rely on getting the CPU frequency from device model.
Fixes #2084
=> fix(ios): update cpu frequency generation logic

ios/MeasureSDK.xcodeproj/project.pbxproj, ios/Sources/MeasureSDK/Swift/LayoutInspector/BaseSvgGenerator.swift, ios/Sources/MeasureSDK/Swift/Utils/Extensions/CGFloat+Extension.swift
Svg generator crashes when it detects a frame with negative x/y coordinates. 
This happens due to swift inferring objc's CGFloat as double, which when converted to Int in certain cases crosses the `Int.min` or `Int.max` limit, leading to a crash.
Fixes #2097
=> fix(ios): update cgfloat to int conversion logic

frontend/dashboard/app/auth/cookie.ts
Safari has stricter requirements than chrome for localhost. This commit relaxes the requirements in dev environment so dashboard can function effectively using Safari.
Fixes #2095
=> fix(frontend): relaxes cookie restricitions in dev

docs/CONTRIBUTING.md
This PR adds a warning banner to contributing guide to direct users interested in just trying out measure to follow the official self host guide.
There was at least one instance of a user who used the contributing guide and found their dashboard crashing after some time.
- fixes #2100
=> docs(backend): add banner in contributing

backend/api/measure/auth.go, backend/api/measure/user.go, docs/api/dashboard/README.md, frontend/dashboard/__tests__/components/__snapshots__/team_switcher_test.tsx.snap, frontend/dashboard/app/[teamId]/layout.tsx, frontend/dashboard/app/auth/measure_auth.ts, frontend/dashboard/app/components/team_switcher.tsx, frontend/dashboard/app/components/user_avatar.tsx
This commit:
- shows logged in user avatar
- shows a dropdown menu on avatar click with logout option
- makes team selector a rounded rect to accommodate avatar
- removed logout from side nav
Closes #2089
=> feat(frontend): show logged in user avatar

self-host/compose.prod.yml
This PR configures production docker compose services to automatically rotate log files after a certain maximum file size threshold (10m) and keep a maximum of 5 files.
- fixes #2111
=> fix(backend): auto rotate compose logs

backend/api/authsession/authsession.go, backend/api/authsession/authstate.go, backend/api/measure/auth.go, backend/api/measure/user.go, docs/api/dashboard/README.md, frontend/dashboard/app/auth/login/google-sign-in.tsx, frontend/dashboard/app/auth/measure_auth.ts, frontend/dashboard/app/components/user_avatar.tsx, frontend/dashboard/next.config.js
This PR:
- adds scopes to get profile pic from google & github
- stores profile pic urls in auth session user metadata
- adds session id to access token
- uses session id from access token to get current session's profile pic url
- Shows profile pic of logged in user on dashboard or shows user name as fallback
- Always uses latest pic from provider without us having to store or update it
Closes #2114
=> feat(frontend): show profile pic of logged in user

backend/api/authsession/authsession.go, backend/api/measure/auth.go, backend/cleanup/cleanup/cleanup.go
Stale auth sessions were being removed on every sign in. This could slow down sign in api if there are a large number of stale auth sessions.
This commit moves the cleanup operation to cleanup service.
Closes #2077
=> chore(backend): delete stale auth sessions in cleanup

backend/api/authsession/authsession.go, backend/api/measure/auth.go
User's default team Id was being stored in the access token. This was unnecessary since we fetch session details from db and this team id can also be fetched from there.
This commit removes own team id from access token and fetches it from db in `/auth/session` api.
Closes #2109
=> chore(backend): remove "Own Team Id" from access token

frontend/dashboard/app/components/session_timeline.tsx, frontend/dashboard/app/components/session_timeline_seekbar.tsx
During a previous formatting change, semicolons were inadvertently removed from css making it invalid and hiding the session timeline seekbar.
This PR adds the missing semicolons.
Fixes #2128
=> fix(frontend): add missing css semicolons

docs/CONTRIBUTING.md
This PR updates the contribution guide to remove a defunct `npm install` command step to avoid certain race conditions leading to a crash of the dashboard service during local development. Additionally, improve the **Troubleshooting** section and document all valid commit scopes.
- fixes #2136
=> docs: remove defunct command from contribution guide

docs/README.md, docs/faqs.md
This PR adds a FAQs page in docs to address frequently asked questions.
- fixes #2140
=> docs: add a faqs page in docs

docs/hosting/README.md
This PR adds a new FAQ entry in Self Hosting Guide to address `client_max_body_size` configuration when using nginx as the reverse proxy.
- fixes #1945
=> docs(backend): add faq for nginx conf in self host guide

frontend/dashboard/app/components/filters.tsx
When we change app name, we reload the page. Filters component finds a persisted selected app which is pointing to the old name and uses it instead of using the new app causing an error.
This commit checks uses the new app name correctly after app name change to avoid the error.
Fixes #2145
=> fix(frontend): fix error on app name change

frontend/dashboard/app/components/filters.tsx
URL filters were being parsed without considering app id. When selected app changes, this lead to invalid filters being applied to newly selected app causing backend to return no data.
This commit adds checks for invalid app id for url filters along with other validity checks to fix this.
Fixes #2147
=> fix(frontend): fix incorrect parsing of url filters

docs/android/README.md
Add guidance to configure `sh.measure.android.API_URL` when connecting to a locally hosted server
Closes #2154
=> docs(android): update readme

frontend/dashboard/app/components/dropdown_select.tsx
Triggering change listeners via useEffect on selected items was causing an infinite loop. This commit fixes it by directly calling the listener where needed.
=> fix(frontend): fix infinite loop in dropdown select

docs/hosting/README.md
This PR updates the self host guide to add a note for podman users on macOS to allocate sufficient memory.
- fixes #2167
=> docs(backend): add low memory note for podman on macos

.github/workflows/api.yml, .github/workflows/cleanup.yml, .github/workflows/dashboard.yml, .github/workflows/lint.yml, .github/workflows/migrator.yml
This PR improves the security of GitHub Workflows by default permissions to `contents: read` instead of `contents: read-write`, as recommended by GitHub's security recommendations.
=> chore(backend): improve workflow security

frontend/dashboard/app/auth/login/google-sign-in.tsx
Google login was being shown before non was calculated. If user quickly tries to login, nonce would not be sent leading to login error. This commit renders the login UI after nonce calculation to fix this issue.
Fixes #2282
=> fix(frontend): show google login after nonce calculation

frontend/dashboard/app/components/filters.tsx
Persisted filters are stored in session storage. When filters component is evaluated by the next js server, it throws an error because session storage is not available in node js. It's a browser only feature.
This commit fixes the issue by checking if window exists before attempting to fetch persisted filters.
=> fix(frontend): check window before accessing persisted filters

frontend/dashboard/__tests__/pages/journeys_overview_test.tsx, frontend/dashboard/__tests__/pages/overview_test.tsx, frontend/dashboard/app/[teamId]/journeys/page.tsx, frontend/dashboard/app/[teamId]/layout.tsx, frontend/dashboard/app/api/api_calls.ts, frontend/dashboard/app/components/bug_reports_overview_plot.tsx, frontend/dashboard/app/components/debounce_text_input.tsx, frontend/dashboard/app/components/exceptions_details_plot.tsx, frontend/dashboard/app/components/exceptions_distribution_plot.tsx, frontend/dashboard/app/components/exceptions_overview_plot.tsx, frontend/dashboard/app/components/journey.tsx, frontend/dashboard/app/components/session_timeline.tsx, frontend/dashboard/app/components/sessions_overview_plot.tsx, frontend/dashboard/app/components/sessions_vs_exceptions_overview_plot.tsx, frontend/dashboard/app/components/span_metrics_plot.tsx
- replaces journey with session vs exceptions graph in overview
- adds a journeys page with journeys
- adds paths and exceptions variants for journeys
- adds journey node search. This allows users to filter nodes. Only nodes matching search text or connecting to matched nodes are displayed.
- removes grids from all graphs
Closes #2202
=> chore(frontend): replace journey with sessions graph in overview

ios/PublicApi/Measure.swiftinterface, ios/Sources/MeasureSDK/Swift/Measure.swift
The `getSessionId` function was intended to be public, but was incorrectly left internal. This PR fixes the issue.
References #1635
=> fix(ios): make session id API public

ios/Scripts/upload_dsym_build_phases.sh
Remove hardcoded `app_unique_id` values from upload dysm script
Fixes #2187
=> fix(ios): remove hardcoded values from upload dysm script

backend/api/measure/bugreport.go, docs/api/dashboard/README.md, self-host/clickhouse/20250618105257_create_new_bug_reports_table.sql, self-host/clickhouse/20250618114246_copy_bug_reports_data_to_new_table.sql, self-host/clickhouse/20250618114324_rename_bug_reports_to_bug_reports_old.sql, self-host/clickhouse/20250618114425_rename_bug_reports_new_to_bug_reports.sql, self-host/clickhouse/20250618114435_drop_bug_reports_mv.sql, self-host/clickhouse/20250618114512_create_bug_reports_mv.sql, self-host/clickhouse/20250618114533_drop_old_bug_reports_table.sql
Bug reports table in clickhouse did not have a versioning column.
This means that clikchouse will by default prioritise insert order.
When we query a bug report with an id and a FINAL clause it will return what it thinks is the correct one which works fine when we are not running distributed clickhouse but will break if we are sharding/partitioning since insert order will depend on which shard/partition we are talking to making it non-deterministic.
We fix this by explicitly adding an `updated_at` column and using that for versioning.
The steps are:
1. Create a new bug reports table (since we can't add versioning column by altering a table)
2. Copy existing bug reports to it
3. Rename current bug reports table to `bug_reports_old`
4. Rename new table to `bug_reports`
5. Drop materialized …
=> chore(backend): add versioning column for bug reports table

android/sample/src/main/java/sh/measure/sample/SampleApp.kt, flutter/example/lib/main.dart, flutter/example/lib/src/screen_main.dart, flutter/packages/measure_dio/test/fake_measure.dart, flutter/packages/measure_flutter/android/src/main/kotlin/sh/measure/flutter/Constants.kt, flutter/packages/measure_flutter/android/src/main/kotlin/sh/measure/flutter/MeasurePlugin.kt, flutter/packages/measure_flutter/ios/Classes/Constants.swift, flutter/packages/measure_flutter/ios/Classes/MeasurePlugin.swift, flutter/packages/measure_flutter/lib/measure.dart, flutter/packages/measure_flutter/lib/src/config/config.dart, flutter/packages/measure_flutter/lib/src/config/config_provider.dart, flutter/packages/measure_flutter/lib/src/config/default_config.dart, flutter/packages/measure_flutter/lib/src/config/measure_config.dart, flutter/packages/measure_flutter/lib/src/config/measure_config.g.dart, flutter/packages/measure_flutter/lib/src/events/custom_event_collector.dart, flutter/packages/measure_flutter/lib/src/exception/exception_collector.dart, flutter/packages/measure_flutter/lib/src/http/http_collector.dart, flutter/packages/measure_flutter/lib/src/measure_api.dart, flutter/packages/measure_flutter/lib/src/measure_initializer.dart, flutter/packages/measure_flutter/lib/src/measure_internal.dart, flutter/packages/measure_flutter/lib/src/method_channel/method_constants.dart, flutter/packages/measure_flutter/lib/src/method_channel/msr_method_channel.dart, flutter/packages/measure_flutter/lib/src/method_channel/msr_platform_interface.dart, flutter/packages/measure_flutter/lib/src/navigation/navigation_collector.dart, flutter/packages/measure_flutter/test/events/custom_event_collector_test.dart, flutter/packages/measure_flutter/test/exception/exception_collector_test.dart, flutter/packages/measure_flutter/test/measure_test.dart, flutter/packages/measure_flutter/test/navigation/navigation_collector_test.dart, flutter/packages/measure_flutter/test/utils/fake_measure.dart, flutter/packages/measure_flutter/test/utils/test_method_channel.dart
* Expose `start` and `stop` APIs.
* Rename the main method to initialize SDK to `init` to be consistent with other SDKs.
Closes #2310
=> feat(flutter): manually start or stop the SDK

android/measure/api/measure.api, android/measure/src/androidTest/java/sh/measure/android/FakeConfigProvider.kt, android/measure/src/androidTest/java/sh/measure/android/MsrBugReportActivityRobot.kt, android/measure/src/androidTest/java/sh/measure/android/MsrBugReportActivityTest.kt, android/measure/src/androidTest/java/sh/measure/android/TestMeasureInitializer.kt, android/measure/src/main/java/sh/measure/android/Measure.kt, android/measure/src/main/java/sh/measure/android/MeasureInitializer.kt, android/measure/src/main/java/sh/measure/android/MeasureInternal.kt, android/measure/src/main/java/sh/measure/android/bugreport/BugReportCollector.kt, android/measure/src/main/java/sh/measure/android/bugreport/MsrBugReportActivity.kt, android/measure/src/main/java/sh/measure/android/bugreport/ShakeBugReportCollector.kt, android/measure/src/main/java/sh/measure/android/config/Config.kt, android/measure/src/main/java/sh/measure/android/config/ConfigProvider.kt, android/measure/src/main/java/sh/measure/android/config/DefaultConfig.kt, android/measure/src/main/java/sh/measure/android/config/MeasureConfig.kt, android/measure/src/test/java/sh/measure/android/bugreport/ShakeBugReportCollectorTest.kt, android/measure/src/test/java/sh/measure/android/fakes/FakeConfigProvider.kt, android/sample/src/main/java/sh/measure/sample/ExceptionDemoActivity.kt, docs/features/feature-bug-report-android.md
⚠️  This is a breaking change. It modifies the public API for launching the bug report UI.
- Removes `enableShakeToLaunchBugReport` config.
- Removes `isShakeToLaunchBugReportEnabled`, `enableShakeToLaunchBugReport` and `disableShakeToLaunchBugReport` methods.
- Clients can use the existing APIs: `setShakeListener` along with `launchBugReport` to effectively do the same.
References #2357
=> chore(android): remove shake to launch bug report config

docs/features/feature-bug-report-ios.md, ios/DemoApp/AppDelegate.swift, ios/PublicApi/Measure.swiftinterface, ios/Sources/MeasureSDK/Swift/BugReport/ShakeBugReportCollector.swift, ios/Sources/MeasureSDK/Swift/BugReport/ShakeDetector.swift, ios/Sources/MeasureSDK/Swift/Config/Config.swift, ios/Sources/MeasureSDK/Swift/Exception/ExceptionGenerator.swift, ios/Sources/MeasureSDK/Swift/Measure.swift, ios/Sources/MeasureSDK/Swift/MeasureInitializer.swift, ios/Sources/MeasureSDK/Swift/MeasureInternal.swift, ios/Tests/MeasureSDKTests/BugReport/ShakeBugReportCollectorTests.swift, ios/Tests/MeasureSDKTests/Mocks/MockMeasureInitializer.swift, ios/Tests/MeasureSDKTests/Mocks/MockShakeDetector.swift
⚠️  This is a breaking change. It modifies the public API for implementing shake listener.
- Remove `MsrShakeListener` protocol.
- Add a `onShake` api with a completion handler which gets called when a shake gesture is detected.
References #2357
=> chore(ios): update shake detector api

ios/DemoApp/SceneDelegate.swift, ios/Sources/MeasureSDK/Swift/Attribute/AppAttributeProcessor.swift, ios/Sources/MeasureSDK/Swift/Attribute/Attribute.swift, ios/Sources/MeasureSDK/Swift/Attribute/AttributeProcessor.swift, ios/Sources/MeasureSDK/Swift/Attribute/ComputeOnceAttributeProcessor.swift, ios/Sources/MeasureSDK/Swift/Attribute/DeviceAttributeProcessor.swift, ios/Sources/MeasureSDK/Swift/Attribute/InstallationIdAttributeProcessor.swift, ios/Sources/MeasureSDK/Swift/Attribute/NetworkStateAttributeProcessor.swift, ios/Sources/MeasureSDK/Swift/Attribute/UserAttributeProcessor.swift, ios/Sources/MeasureSDK/Swift/Events/Event.swift, ios/Sources/MeasureSDK/Swift/Events/InternalSignalCollector.swift, ios/Sources/MeasureSDK/Swift/Events/SignalProcessor.swift, ios/Sources/MeasureSDK/Swift/Exporter/NetworkClient.swift, ios/Sources/MeasureSDK/Swift/Tracing/SpanProcessor.swift, ios/Sources/MeasureSDK/Swift/Utils/SystemFileManager.swift, ios/Tests/MeasureSDKTests/Attribute/AttributeProcessorTests.swift, ios/Tests/MeasureSDKTests/Attribute/ComputeOnceAttributeProcessorTests.swift, ios/Tests/MeasureSDKTests/Attribute/InstallationIdAttributeProcessorTests.swift, ios/Tests/MeasureSDKTests/Attribute/UserAttributeProcessorTests.swift, ios/Tests/MeasureSDKTests/Exporter/HttpClientTests.swift, ios/Tests/MeasureSDKTests/Mocks/MockAttributeProcessor.swift, measure-sh.podspec
This PR contains the below changes
- Fix network attributes being set to nil when first event is tracked.
- Fix empty thread name.
- Update `Attribute` to be a class instead of a struct. The reason for doing is that classes are passed by reference and structs are passed by value. Given that the event object passes a single attribute object across multiple attribute processors to be updated, it makes more sense for it to be a class rather than a struct.
Fixes #2366
=> fix(ios): generate non nil network attributes for first event

ios/Sources/MeasureSDK/Swift/LayoutInspector/BaseSvgGenerator.swift
SDK crashes randomly when trying to generate layout snapshot. This happens when float value when converted to int exceeds the Int limit. This PR fixes the same.
Fixes #2380
=> fix(ios): convert float to int safely

android/measure/api/measure.api, android/measure/src/main/java/sh/measure/android/config/MeasureConfig.kt
To allow Flutter to configure the native SDK during initialization we made `MeasureConfig` implement `@Serializable`. This leaks the serialization details in the public API which is not ideal. To hide the serialization details from public API, a new internal wrapper has been introduced over `MeasureConfig` which instead handles serialization.
This makes adding new configs a bit harder, but this can be solved later using a annotation processor to generate code.
Closes #2384
=> chore(android): hide config serialization from public api

flutter/packages/measure_flutter/lib/src/gestures/msr_gesture_detector.dart, flutter/packages/measure_flutter/lib/src/method_channel/signal_processor.dart, flutter/packages/measure_flutter/test/gestures/msr_gesture_detector_test.dart
- Earlier local coordinates of the widget were being reported instead of the actual screen coordinates.
- Also removes a redundant log.
Closes #2382
=> fix(flutter): gesture positions to represent device coordinates

flutter/example/lib/src/dio_interceptor.dart
Fix warnings on main which are causing the CI to fail. This issue started after merging #2361.
References #2361
=> chore(flutter): use correct import for measure_flutter

flutter/example/ios/Podfile.lock, flutter/packages/measure_flutter/lib/src/gestures/msr_gesture_detector.dart, ios/Sources/MeasureSDK/Swift/Gestures/GestureCollector.swift, ios/Sources/MeasureSDK/Swift/Gestures/GestureTargetFinder.swift
- use explicitly set widget names instead of relying on runtime type to avoid obfuscated
names
- discard ios gestures on flutter views
Fixes #2393 and Fixes #2392
=> chore(flutter): fix gesture events reporting

.github/workflows/android-prepare-release.yml
Attempt to fix the prepare release action which still fails after the previous update in #2402 
- Removed the manual branch creation: Don't create the branch manually with git checkout -b
- Removed the manual commit: Don't commit manually
- Let create-pull-request handle everything: The action will create the branch, commit the changes, and create the PR
=> ci(flutter): fix prepare release command

docs/hosting/smtp-email.md
This PR extends the SMTP page of the self host guide to instruct how to configure SMTP environment variables for users upgrading from v0.7.x.
- fixes #2411
=> docs(backend): add smtp configuration to self host guide

flutter/packages/measure_flutter/lib/src/config/config.dart, flutter/packages/measure_flutter/lib/src/config/config_provider.dart, flutter/packages/measure_flutter/lib/src/config/default_config.dart, flutter/packages/measure_flutter/lib/src/config/internal_config.dart, flutter/packages/measure_flutter/lib/src/events/custom_event_collector.dart, flutter/packages/measure_flutter/lib/src/events/msr_attachment.dart, flutter/packages/measure_flutter/lib/src/measure_initializer.dart, flutter/packages/measure_flutter/test/events/custom_event_collector_test.dart, flutter/packages/measure_flutter/test/utils/fake_config_provider.dart
Add missing validations for custom event names.
- Max length
- Empty name
- Event name should follow expected regex
This PR also updates documentation for attachment which had an incorrect example.
Fixes #2434
=> chore(flutter): add validations for custom events

.github/workflows/android-checks.yml, android/measure-android-gradle/src/functionalTest/kotlin/sh/measure/MeasurePluginTest.kt, android/measure-android-gradle/src/functionalTest/kotlin/sh/measure/fixtures/MeasurePluginFixture.kt, android/measure-android-gradle/src/test/kotlin/sh/measure/BuildUploadTaskTest.kt
- Fix functional tests and reduce the number of gradle versions on which they are run
- Run plugin unit tests on CI 
Closes #2448
=> chore(gradle): fix tests and run them on ci

ios/Sources/MeasureSDK/Swift/Lifecycle/LifecycleCollector.swift
Adds some new internal view controllers to be ignored from reporting. This helps us to keep journey graphs reflect what developers would expect.
References: #2456
=> chore(ios): add more view controllers to be ignored

android/measure/src/main/java/sh/measure/android/applaunch/LaunchTracker.kt
Use `System.currentTimeMillis()` instead of `SystemClock.elapsedRealtime()`. This causes the different clock times to be compared for launch metrics calculation.
This issue started occurring since: https://github.com/measure-sh/measure/pull/2386 (released in `android-v0.11.0`).
This fix is planned for release in `android-v0.11.1`.
- We almost never want to use `System.currentTimeMillis()`, adding a detekt rule would help: #2474 
Fixes #2472
=> fix(android): use correct timestamp for launch metric calculation

docs/hosting/README.md
This PR adds a new FAQ entry in self host guide on how to add/update environment variables and restart services to take effect.
- fixes #2479
=> docs(backend): add faq on updating environment variables

docs/features/feature-custom-events.md, docs/features/feature-performance-tracing.md
This PR updates user facing documentation to create awareness about character restrictions when choosing user defined attribute keys.
- fixes #2478
=> docs: document attribute key restrictions

ios/PublicApi/Measure.swiftinterface, ios/Sources/MeasureSDK/Swift/Config/BaseConfigProvider.swift, ios/Sources/MeasureSDK/Swift/Config/Config.swift, ios/Sources/MeasureSDK/Swift/Config/DefaultConfig.swift, ios/Sources/MeasureSDK/Swift/Config/InternalConfig.swift, ios/Sources/MeasureSDK/Swift/Config/MeasureConfig.swift, ios/Sources/MeasureSDK/Swift/CoreData/DataCleanupService.swift, ios/Sources/MeasureSDK/Swift/CoreData/EventStore.swift, ios/Sources/MeasureSDK/Swift/CoreData/SpanStore.swift, ios/Sources/MeasureSDK/Swift/MeasureInitializer.swift, ios/Tests/MeasureSDKTests/CoreData/DataCleanupServiceTests.swift, ios/Tests/MeasureSDKTests/Mocks/MockConfigProvider.swift, ios/Tests/MeasureSDKTests/Mocks/MockEventStore.swift, ios/Tests/MeasureSDKTests/Mocks/MockMeasureInitializer.swift, ios/Tests/MeasureSDKTests/Mocks/MockSpanStore.swift
- adds a new public config (maxDiskUsageInMb)
- adds a internal config (estimatedEventSizeInKb)
- updates data cleanup logic
Closes #2442
=> feat(ios): provide configurable storage limits

android/measure-android-gradle/src/main/kotlin/sh/measure/DependencyUtils.kt, android/measure-android-gradle/src/main/kotlin/sh/measure/asm/NavigationTransformer.kt, android/measure-android-gradle/src/main/kotlin/sh/measure/asm/OkHttpTransformer.kt, android/measure-android-gradle/src/main/kotlin/sh/measure/asm/VersionAwareVisitor.kt
Fixes ASM transformation not being applied to dependencies managed by Bill of Materials (BOM). Previously, version parsing for BOM-managed dependencies always resulted in null, causing version compatibility checks to fail and preventing instrumentation.
The issue occurred because the version resolution logic only checked the requested version from direct dependencies. For BOM-managed dependencies declared without explicit versions, the requested version is empty and the actual version is determined during dependency resolution. Updated the parsing to fall back to the resolved component version when the requested version is unavailable.
Also adds some logs to make it easier to debug such issues in future.
Fixes #2512
=> fix(android): resolve instrumentation failure with BOM dependencies

ios/Sources/MeasureSDK/Swift/Screenshots/ScreenshotGenerator.swift
Remove deprecated UIWebView API usage to fix inability to publish iOS app to apple.
Fixes #2536
=> fix(ios): remove deprecated UIWebView usage

android/measure/src/main/java/sh/measure/android/tracing/SpanProcessor.kt, android/measure/src/test/java/sh/measure/android/tracing/MsrSpanProcessorTest.kt
Discards invalid spans created with empty name and logs an error.
Fixes #2526
=> fix(android): discard span with empty name

android/measure-android-gradle/src/main/kotlin/sh/measure/BuildUploadTask.kt, android/measure-android-gradle/src/test/kotlin/sh/measure/BuildUploadTaskTest.kt
Fixes invalid api-key error for `/builds` API. The _Authorization_ header was getting filtered after this PR: #2343 was merged.
Fixes #2548
=> fix(gradle): prevent authorization header from getting filtered

android/measure/src/main/java/sh/measure/android/applaunch/LaunchTracker.kt
This reverts commit d619e6ed5ff4074677cc4b38bb75400497aaeee8 added in PR: #2473.
This change is not needed as the event timestamp is irrelevant to launch time calculation. Using the wall clock time is the correct behaviour.
References #2473
=> Revert "fix(android): use correct timestamp for launch metric calculation (#2473)

android/measure/src/main/java/sh/measure/android/bugreport/MsrBugReportActivity.kt, android/measure/src/main/java/sh/measure/android/exceptions/UnhandledExceptionCollector.kt, android/measure/src/test/java/sh/measure/android/exceptions/UnhandledExceptionCollectorTest.kt
Without peristable permission, images being selected using multi-select API were not being tracked.
- Ensure media picker URIs have persistable permission to allow reading the image for storage.
- Fix validation to use both initial screenshot and selected uris.
References #2502
=> fix(android): take persistable permission for uris

.github/workflows/android-checks.yml, .github/workflows/android-prepare-release.yml, android/CHANGELOG.md, android/cliff.toml, android/gradle.properties, android/gradle/libs.versions.toml, docs/sdk-integration-guide.md
This PR prepares the Android SDK for release version 0.12.0.
Changes:
- Updated version to 0.12.0 in gradle.properties
- Updated version in README.md
- Updated version in libs.versions.toml
- Add changelog
=> chore(android): prepare sdk release 0.12.0

android/measure/src/main/java/sh/measure/android/MeasureInternal.kt, android/measure/src/main/java/sh/measure/android/SessionManager.kt, android/measure/src/main/java/sh/measure/android/SessionStartData.kt, android/measure/src/main/java/sh/measure/android/config/Config.kt, android/measure/src/main/java/sh/measure/android/events/CustomEventCollector.kt, android/measure/src/main/java/sh/measure/android/events/EventType.kt, android/measure/src/main/java/sh/measure/android/events/SignalProcessor.kt, android/measure/src/main/java/sh/measure/android/storage/EventExtensions.kt, android/measure/src/test/java/sh/measure/android/SessionManagerTest.kt, android/measure/src/test/java/sh/measure/android/fakes/FakeSessionManager.kt
- Tracks a `session_start` event when a new session is created.
- Always send `session_start` event regardless of sampling conditions.
- Also updates event and span processing logs for easier debugging.
Closes #2572
=> feat(android): track session start event

ios/DemoApp/Controller/ControlsViewController.swift, ios/Sources/MeasureSDK/Swift/LayoutInspector/BaseSvgGenerator.swift, ios/Sources/MeasureSDK/Swift/LayoutInspector/LayoutSnapshotGenerator.swift, ios/Tests/MeasureSDKTests/Mocks/MockSvgGenerator.swift
When we generated layout snapshots earlier, we would collect all the frames in the current view hierarchy, check which view had the maximum X or Y coordinates and generate the SVG's viewBox height and width according to it. The idea behind this was that if any view was lurking in the background, that would be captured as well, as shown in the below screenshot.
The problem with the above approach is that in some cases ios system views like pickers, maps, tableviews maintain a huge canvas in background outside the scope of the current screen. This leads to huge viewBox size especially in case of iPads and Macbooks. This is now fixed in this PR by making sure that we set the viewBox dimensions to the current size of the screen instead on the canvas dimensions. New layout snapshot for the …
=> fix(ios): fix blank svg generation

ios/Sources/MeasureSDK/Swift/Utils/Extensions/UIApplication+Extension.swift
We are swizzling UIApplication.sendEvent(_:) using .replace swizzling strategy. This replaces the implementation of sendEvent(_:) with our swizzled_sendEvent(_:), and records the old implementation. Inside our swizzled_sendEvent(_:), we manually call the old implementation. The crash suggests that the old implementation could not be found.
To fix this, we'll use `method_exchangeImplementations` instead of `class_replaceMethod` for swizzling and call the old implementation in the new implementation itself, there by removing the need for maintaining a copy of the old implementation.
Fixes #2584
=> fix(ios): add safe uiapplication swizzling

docs/features/feature-app-launch-metrics.md, ios/Sources/MeasureSDK/Swift/AppLaunch/LaunchTracker.swift, ios/Sources/MeasureSDK/Swift/Utils/SysCtl.swift
This PR fixes incorrect launch time by updating the below things:
- Update sysCtl's `getProcessStartTime` to provide more accurate process start time.
- Ignore launch time collection if the app is [pre-warmed](https://developer.apple.com/documentation/uikit/about-the-app-launch-sequence#Prepare-your-app-for-prewarming)
- Use `timeProvider` instead of `Date().timeIntervalSince1970`
Fixes #2561
=> fix(ios): update process start time logic

ios/MeasureSDK.xcodeproj/project.pbxproj, ios/PublicApi/Measure.swiftinterface, ios/Sources/MeasureSDK/Swift/Lifecycle/LifecycleManager.swift, ios/Sources/MeasureSDK/Swift/Lifecycle/LifecycleManagerInternal.swift
Add proper implementation for objc class LifecycleManagerInternal in swift.
Fixes #2602
=> fix(ios): add proper implementation for LifecycleManagerInternal

self-host/sessionator/cmd/ingest.go
This PR fixes the endpoint to upload builds in sessionator. It was pointing to a non-existent route.
- fixes #2611
=> fix(backend): update builds upload endpoint in sessionator

backend/api/measure/event.go
This PR updates the ingestion metrics insert to write data asynchronously into the table.
- fixes #2610
=> fix(backend): insert metrics asynchronously

docs/CONTRIBUTING.md, self-host/session-data/config.toml.example
This PR updates the contributing guide and sessionator example config with latest correct state.
- fixes #2614
=> docs(backend): update sessionator example config

backend/alerts/main.go
Check for alerts at start of every hour instead of hourly since service start. This will lead to more consistent alert creation behaviour.
Closes #2616
=> chore(backend): check for alerts at start of every hour

ios/Sources/MeasureSDK/Swift/AppLaunch/AppLaunchCollector.swift, ios/Sources/MeasureSDK/Swift/AppLaunch/LaunchTracker.swift, ios/Sources/MeasureSDK/Swift/Config/Config.swift, ios/Sources/MeasureSDK/Swift/MeasureInternal.swift, ios/Sources/MeasureSDK/Swift/Utils/LifecycleObserver.swift, ios/Tests/MeasureSDKTests/Config/BaseConfigProviderTests.swift
This PR contains the below changes
- Disable all collectors when app moves to background
- Reduce session stitching duration to 3 minutes
- Update launch time generation logic
Fixes #2631
=> fix(ios): track proper session duration

android/measure/src/androidTest/java/sh/measure/android/FakeConfigProvider.kt, android/measure/src/androidTest/java/sh/measure/android/SessionTest.kt, android/measure/src/androidTest/java/sh/measure/android/SessionTestRobot.kt, android/measure/src/main/java/sh/measure/android/SessionManager.kt, android/measure/src/main/java/sh/measure/android/config/Config.kt, android/measure/src/main/java/sh/measure/android/config/ConfigProvider.kt, android/measure/src/main/java/sh/measure/android/config/InternalConfig.kt, android/measure/src/test/java/sh/measure/android/SessionManagerTest.kt, android/measure/src/test/java/sh/measure/android/fakes/FakeConfigProvider.kt, docs/features/feature-session-monitoring.md
Changes the following internal configs.
1. `sessionEndLastEventThresholdMs` from 20 mins to 3 minutes
2. Remove `maxSessionDurationMs` as it is no longer required with the reduced `sessionEndLastEventThresholdMs`.
3. Updates session documentation.
Closes #2586
=> chore(android): update session configs
